# Importing Dataset

In [288]:
import pandas as pd 

In [289]:
df = pd.read_csv(r'D:\My Drive\healthcare_dataset.csv')
df 

Name  Age  Gender Blood Type Medical Condition  \
0          Tiffany Ramirez   81  Female         O-          Diabetes   
1              Ruben Burns   35    Male         O+            Asthma   
2                Chad Byrd   61    Male         B-           Obesity   
3        Antonio Frederick   49    Male         B-            Asthma   
4      Mrs. Brandy Flowers   51    Male         O-         Arthritis   
...                    ...  ...     ...        ...               ...   
9995            James Hood   83    Male         A+           Obesity   
9996       Stephanie Evans   47  Female        AB+         Arthritis   
9997  Christopher Martinez   54    Male         B-         Arthritis   
9998           Amanda Duke   84    Male         A+         Arthritis   
9999             Eric King   20    Male         B-         Arthritis   

     Date of Admission             Doctor                   Hospital  \
0           2022-11-17     Patrick Parker           Wallace-Hamilton   
1           2023-06-01      Diane Jackson  Burke, Griffin and Cooper   
2           2019-01-09         Paul Baker                 Walton LLC   
3           2020-05-02     Brian Chandler                 Garcia Ltd   
4           2021-07-09     Dustin Griffin    Jones, Brown and Murray   
...                ...                ...                        ...   
9995        2022-07-29       Samuel Moody   Wood, Martin and Simmons   
9996        2022-01-06  Christopher Yates               Nash-Krueger   
9997        2022-07-01   Robert Nicholson            Larson and Sons   
9998        2020-02-06        Jamie Lewis               Wilson-Lyons   
9999        2023-03-22        Tasha Avila  Torres, Young and Stewart   

     Insurance Provider  Billing Amount  Room Number Admission Type  \
0              Medicare    37490.983364          146       Elective   
1      UnitedHealthcare    47304.064845          404      Emergency   
2              Medicare    36874.896997          292      Emergency   
3              Medicare    23303.322092          480         Urgent   
4      UnitedHealthcare    18086.344184          477         Urgent   
...                 ...             ...          ...            ...   
9995   UnitedHealthcare    39606.840083          110       Elective   
9996         Blue Cross     5995.717488          244      Emergency   
9997         Blue Cross    49559.202905          312       Elective   
9998   UnitedHealthcare    25236.344761          420         Urgent   
9999              Aetna    37223.965865          290      Emergency   

     Discharge Date   Medication  Test Results  
0        2022-12-01      Aspirin  Inconclusive  
1        2023-06-15      Lipitor        Normal  
2        2019-02-08      Lipitor        Normal  
3        2020-05-03   Penicillin      Abnormal  
4        2021-08-02  Paracetamol        Normal  
...             ...          ...           ...  
9995     2022-08-02    Ibuprofen      Abnormal  
9996     2022-01-29    Ibuprofen        Normal  
9997     2022-07-15    Ibuprofen        Normal  
9998     2020-02-26   Penicillin        Normal  
9999     2023-04-15   Penicillin      Abnormal  

[10000 rows x 15 columns]

# Dataset Analysis

In [290]:
df.isnull().sum()

Name                  0
Age                   0
Gender                0
Blood Type            0
Medical Condition     0
Date of Admission     0
Doctor                0
Hospital              0
Insurance Provider    0
Billing Amount        0
Room Number           0
Admission Type        0
Discharge Date        0
Medication            0
Test Results          0
dtype: int64

In [291]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Name                10000 non-null  object 
 1   Age                 10000 non-null  int64  
 2   Gender              10000 non-null  object 
 3   Blood Type          10000 non-null  object 
 4   Medical Condition   10000 non-null  object 
 5   Date of Admission   10000 non-null  object 
 6   Doctor              10000 non-null  object 
 7   Hospital            10000 non-null  object 
 8   Insurance Provider  10000 non-null  object 
 9   Billing Amount      10000 non-null  float64
 10  Room Number         10000 non-null  int64  
 11  Admission Type      10000 non-null  object 
 12  Discharge Date      10000 non-null  object 
 13  Medication          10000 non-null  object 
 14  Test Results        10000 non-null  object 
dtypes: float64(1), int64(2), object(12)
memory usage: 1.1+

# Data Cleaning

In [292]:
df.drop(columns=['Name','Date of Admission','Doctor','Hospital','Insurance Provider','Billing Amount','Room Number','Discharge Date'],inplace=True)
df 

Age  Gender Blood Type Medical Condition Admission Type   Medication  \
0      81  Female         O-          Diabetes       Elective      Aspirin   
1      35    Male         O+            Asthma      Emergency      Lipitor   
2      61    Male         B-           Obesity      Emergency      Lipitor   
3      49    Male         B-            Asthma         Urgent   Penicillin   
4      51    Male         O-         Arthritis         Urgent  Paracetamol   
...   ...     ...        ...               ...            ...          ...   
9995   83    Male         A+           Obesity       Elective    Ibuprofen   
9996   47  Female        AB+         Arthritis      Emergency    Ibuprofen   
9997   54    Male         B-         Arthritis       Elective    Ibuprofen   
9998   84    Male         A+         Arthritis         Urgent   Penicillin   
9999   20    Male         B-         Arthritis      Emergency   Penicillin   

      Test Results  
0     Inconclusive  
1           Normal  
2           Normal  
3         Abnormal  
4           Normal  
...            ...  
9995      Abnormal  
9996        Normal  
9997        Normal  
9998        Normal  
9999      Abnormal  

[10000 rows x 7 columns]

In [293]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   Age                10000 non-null  int64 
 1   Gender             10000 non-null  object
 2   Blood Type         10000 non-null  object
 3   Medical Condition  10000 non-null  object
 4   Admission Type     10000 non-null  object
 5   Medication         10000 non-null  object
 6   Test Results       10000 non-null  object
dtypes: int64(1), object(6)
memory usage: 547.0+ KB


In [294]:
df['Gender'].value_counts()

Female    5075
Male      4925
Name: Gender, dtype: int64

In [295]:
df['Blood Type'].value_counts()

AB-    1275
AB+    1258
B-     1252
O+     1248
O-     1244
B+     1244
A+     1241
A-     1238
Name: Blood Type, dtype: int64

In [296]:
df['Medical Condition'].value_counts()

Asthma          1708
Cancer          1703
Hypertension    1688
Arthritis       1650
Obesity         1628
Diabetes        1623
Name: Medical Condition, dtype: int64

In [297]:
df['Admission Type'].value_counts()

Urgent       3391
Emergency    3367
Elective     3242
Name: Admission Type, dtype: int64

In [298]:
df['Medication'].value_counts()

Penicillin     2079
Lipitor        2015
Ibuprofen      1976
Aspirin        1968
Paracetamol    1962
Name: Medication, dtype: int64

In [299]:
df['Test Results'].value_counts() 

Abnormal        3456
Inconclusive    3277
Normal          3267
Name: Test Results, dtype: int64

In [300]:
df = pd.get_dummies(df,columns=['Gender','Blood Type','Medical Condition','Admission Type','Medication'],drop_first=True)
df 

Age  Test Results  Gender_Male  Blood Type_A-  Blood Type_AB+  \
0      81  Inconclusive            0              0               0   
1      35        Normal            1              0               0   
2      61        Normal            1              0               0   
3      49      Abnormal            1              0               0   
4      51        Normal            1              0               0   
...   ...           ...          ...            ...             ...   
9995   83      Abnormal            1              0               0   
9996   47        Normal            0              0               1   
9997   54        Normal            1              0               0   
9998   84        Normal            1              0               0   
9999   20      Abnormal            1              0               0   

      Blood Type_AB-  Blood Type_B+  Blood Type_B-  Blood Type_O+  \
0                  0              0              0              0   
1                  0              0              0              1   
2                  0              0              1              0   
3                  0              0              1              0   
4                  0              0              0              0   
...              ...            ...            ...            ...   
9995               0              0              0              0   
9996               0              0              0              0   
9997               0              0              1              0   
9998               0              0              0              0   
9999               0              0              1              0   

      Blood Type_O-  ...  Medical Condition_Cancer  \
0                 1  ...                         0   
1                 0  ...                         0   
2                 0  ...                         0   
3                 0  ...                         0   
4                 1  ...                         0   
...             ...  ...                       ...   
9995              0  ...                         0   
9996              0  ...                         0   
9997              0  ...                         0   
9998              0  ...                         0   
9999              0  ...                         0   

      Medical Condition_Diabetes  Medical Condition_Hypertension  \
0                              1                               0   
1                              0                               0   
2                              0                               0   
3                              0                               0   
4                              0                               0   
...                          ...                             ...   
9995                           0                               0   
9996                           0                               0   
9997                           0                               0   
9998                           0                               0   
9999                           0                               0   

      Medical Condition_Obesity  Admission Type_Emergency  \
0                             0                         0   
1                             0                         1   
2                             1                         1   
3                             0                         0   
4                             0                         0   
...                         ...                       ...   
9995                          1                         0   
9996                          0                         1   
9997                          0                         0   
9998                          0                         0   
9999                          0                         1   

      Admission Type_Urgent  Medication_Ibuprofen  Medication_Lipitor  \
0                         0                     0   

In [301]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 21 columns):
 #   Column                          Non-Null Count  Dtype 
---  ------                          --------------  ----- 
 0   Age                             10000 non-null  int64 
 1   Test Results                    10000 non-null  object
 2   Gender_Male                     10000 non-null  uint8 
 3   Blood Type_A-                   10000 non-null  uint8 
 4   Blood Type_AB+                  10000 non-null  uint8 
 5   Blood Type_AB-                  10000 non-null  uint8 
 6   Blood Type_B+                   10000 non-null  uint8 
 7   Blood Type_B-                   10000 non-null  uint8 
 8   Blood Type_O+                   10000 non-null  uint8 
 9   Blood Type_O-                   10000 non-null  uint8 
 10  Medical Condition_Asthma        10000 non-null  uint8 
 11  Medical Condition_Cancer        10000 non-null  uint8 
 12  Medical Condition_Diabetes      10000 non-null 

# Defining X & y for Training and Testing Dataset

In [302]:
X = df.drop(columns='Test Results')
X 

Age  Gender_Male  Blood Type_A-  Blood Type_AB+  Blood Type_AB-  \
0      81            0              0               0               0   
1      35            1              0               0               0   
2      61            1              0               0               0   
3      49            1              0               0               0   
4      51            1              0               0               0   
...   ...          ...            ...             ...             ...   
9995   83            1              0               0               0   
9996   47            0              0               1               0   
9997   54            1              0               0               0   
9998   84            1              0               0               0   
9999   20            1              0               0               0   

      Blood Type_B+  Blood Type_B-  Blood Type_O+  Blood Type_O-  \
0                 0              0              0              1   
1                 0              0              1              0   
2                 0              1              0              0   
3                 0              1              0              0   
4                 0              0              0              1   
...             ...            ...            ...            ...   
9995              0              0              0              0   
9996              0              0              0              0   
9997              0              1              0              0   
9998              0              0              0              0   
9999              0              1              0              0   

      Medical Condition_Asthma  Medical Condition_Cancer  \
0                            0                         0   
1                            1                         0   
2                            0                         0   
3                            1                         0   
4                            0                         0   
...                        ...                       ...   
9995                         0                         0   
9996                         0                         0   
9997                         0                         0   
9998                         0                         0   
9999                         0                         0   

      Medical Condition_Diabetes  Medical Condition_Hypertension  \
0                              1                               0   
1                              0                               0   
2                              0                               0   
3                              0                               0   
4                              0                               0   
...                          ...                             ...   
9995                           0                               0   
9996                           0                               0   
9997                           0                               0   
9998                           0                               0   
9999                           0                               0   

      Medical Condition_Obesity  Admission Type_Emergency  \
0                             0                         0   
1                             0                         1   
2                             1                         1   
3                             0                         0   
4                             0                         0   
...                         ...                       ...   
9995                          1                         0   
9996                          0                         1   
9997                          0                         0   
9998                          0                         0   
9999                          0                         1   

      Admission Type_Urgent  Medication_I

In [303]:
y = df[['Test Results']]
y 

Test Results
0     Inconclusive
1           Normal
2           Normal
3         Abnormal
4           Normal
...            ...
9995      Abnormal
9996        Normal
9997        Normal
9998        Normal
9999      Abnormal

[10000 rows x 1 columns]

# Split Dataset into Training & Testing 

In [304]:
from sklearn.model_selection import train_test_split 

In [305]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0) 

# Data Preprocessing

In [306]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler.fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)
X_train_scaled = pd.DataFrame(X_train_scaled)
X_test_scaled = pd.DataFrame(X_test_scaled)

In [307]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_train_scaled = le.fit_transform(y_train)
y_test_scaled = le.fit_transform(y_test) 
y_train_scaled = pd.DataFrame(y_train_scaled)
y_test_scaled = pd.DataFrame(y_test_scaled)

c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [308]:
X_train_scaled 

0    1    2    3    4    5    6    7    8    9    10   11   12  \
0     0.298507  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0   
1     0.074627  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0   
2     0.089552  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0   
3     0.208955  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0   
4     0.850746  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0   
...        ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
7995  0.104478  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
7996  0.641791  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0   
7997  0.940299  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0   
7998  0.104478  1.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   
7999  0.238806  1.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0   

       13   14   15   16   17   18   19  
0     0.0  0.0  0.0  0.0  1.0  0.0  0.0  
1     0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2     0.0  0.0  0.0  0.0  1.0  0.0  0.0  
3     0.0  0.0  0.0  0.0  0.0  1.0  0.0  
4     0.0  0.0  1.0  0.0  1.0  0.0  0.0  
...   ...  ...  ...  ...  ...  ...  ...  
7995  0.0  0.0  1.0  0.0  0.0  1.0  0.0  
7996  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
7997  0.0  0.0  0.0  0.0  1.0  0.0  0.0  
7998  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
7999  0.0  1.0  0.0  0.0  0.0  0.0  1.0  

[8000 rows x 20 columns]

In [309]:
X_test_scaled 

0    1    2    3    4    5    6    7    8    9    10   11   12  \
0     0.029851  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0   
1     0.149254  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  0.0  0.0   
2     0.253731  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  1.0   
3     0.880597  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0   
4     0.134328  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0   
...        ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
1995  0.955224  1.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  1.0   
1996  0.686567  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0   
1997  0.149254  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0   
1998  0.835821  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   
1999  1.000000  1.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0   

       13   14   15   16   17   18   19  
0     0.0  0.0  1.0  0.0  0.0  1.0  0.0  
1     0.0  0.0  1.0  1.0  0.0  0.0  0.0  
2     0.0  0.0  0.0  0.0  0.0  0.0  1.0  
3     0.0  1.0  0.0  0.0  0.0  1.0  0.0  
4     1.0  0.0  1.0  0.0  0.0  0.0  1.0  
...   ...  ...  ...  ...  ...  ...  ...  
1995  0.0  0.0  1.0  1.0  0.0  0.0  0.0  
1996  0.0  0.0  0.0  0.0  0.0  1.0  0.0  
1997  0.0  0.0  1.0  0.0  0.0  0.0  1.0  
1998  0.0  0.0  1.0  0.0  0.0  0.0  1.0  
1999  0.0  0.0  0.0  1.0  0.0  0.0  0.0  

[2000 rows x 20 columns]

# Multiple Linear Regression 

In [310]:
from sklearn.linear_model import LinearRegression

In [311]:
lr = LinearRegression() 

In [312]:
model = lr.fit(X_train_scaled,y_train_scaled) 

In [313]:
y_pred = lr.predict(X_test_scaled)
y_pred  

array([[0.94034261],
       [0.97256227],
       [0.96234217],
       ...,
       [1.0028203 ],
       [1.00175399],
       [1.0193901 ]])

In [314]:
train_acc = lr.predict(X_train_scaled)
train_acc 

array([[0.91715359],
       [0.97735867],
       [0.96510356],
       ...,
       [0.97464492],
       [0.9937158 ],
       [0.92738239]])

Evaultion

In [315]:
from sklearn.metrics import r2_score,mean_squared_error
import numpy as np  

In [316]:
print('R2_Score: ',r2_score(y_test_scaled,y_pred))
print('MSE: ',np.sqrt(mean_squared_error(y_test_scaled,y_pred))) 

R2_Score:  -0.000654055438528367
MSE:  0.8220105883210427


Real Data Prediction

In [317]:
lr.predict(pd.DataFrame([[0.686567,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0]]))

array([[1.07026774]])

# Polinomial Regression

In [318]:
from sklearn.preprocessing import PolynomialFeatures 

In [319]:
poly = PolynomialFeatures(degree=2)
X_train_poly = poly.fit_transform(X_train_scaled)
X_test_poly = poly.fit_transform(X_test_scaled) 

In [320]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
model = lr.fit(X_train_poly,y_train_scaled) 

In [321]:
y_pred =lr.predict(X_test_poly)
y_pred 

array([[1.09157813],
       [1.04860938],
       [0.9099375 ],
       ...,
       [0.9255625 ],
       [1.09548438],
       [0.93532813]])

In [322]:
train_acc = lr.predict(X_train_poly)
train_acc 

array([[0.98220313],
       [1.00173438],
       [0.78298438],
       ...,
       [1.33767188],
       [0.82985938],
       [1.00759375]])

Evaultion

In [323]:
from sklearn.metrics import r2_score,mean_squared_error

In [324]:
print('R2_Score: ',r2_score(y_test_scaled,y_pred))
print('MSE: ',np.sqrt(mean_squared_error(y_test_scaled,y_pred))) 

R2_Score:  -0.026111590001343332
MSE:  0.8324012588508078


Real Data Prediction

In [325]:
lr.predict(poly.transform([[0.686567,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0]]))

array([[1.10354102]])

# RIDGE

In [326]:
from sklearn.linear_model import Ridge
r=Ridge(alpha=0.0001) 

In [327]:
r.fit(X_train_scaled,y_train_scaled) 

Ridge(alpha=0.0001)

In [328]:
y_pred = r.predict(X_test_scaled) 
y_pred 

array([[0.94034262],
       [0.97256228],
       [0.96234217],
       ...,
       [1.00282027],
       [1.00175399],
       [1.0193901 ]])

In [329]:
train_acc = r.predict(X_train_scaled)
train_acc 

array([[0.9171536 ],
       [0.97735867],
       [0.96510356],
       ...,
       [0.97464493],
       [0.9937158 ],
       [0.9273824 ]])

Evaultion

In [330]:
print('R2_Score: ',r2_score(y_test_scaled,y_pred))
print('MSE: ',np.sqrt(mean_squared_error(y_test_scaled,y_pred))) 

R2_Score:  -0.0006540555780230051
MSE:  0.8220105883783383


Real Data Prediction

In [331]:
r.predict(pd.DataFrame([[0.686567,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0]]))

array([[1.07026771]])

# LASSO

In [332]:
from sklearn.linear_model import Lasso 
l = Lasso(alpha=0.01)

In [333]:
l.fit(X_train_scaled,y_train_scaled) 

Lasso(alpha=0.01)

In [334]:
y_pred = l.predict(X_test_scaled) 
y_pred 

array([0.98025, 0.98025, 0.98025, ..., 0.98025, 0.98025, 0.98025])

In [335]:
train_acc = l.predict(X_train_scaled)
train_acc 

array([0.98025, 0.98025, 0.98025, ..., 0.98025, 0.98025, 0.98025])

Evaultion

In [336]:
print('R2_Score: ',r2_score(y_test_scaled,y_pred))
print('MSE: ',np.sqrt(mean_squared_error(y_test_scaled,y_pred))) 

R2_Score:  -2.6748965860967644e-05
MSE:  0.8217528901683279


Real Data Prediction

In [337]:
l.predict(pd.DataFrame([[0.686567,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0]]))

array([0.98025])

# Decision Tree

In [338]:
from sklearn.tree import DecisionTreeClassifier 

In [339]:
classifier = DecisionTreeClassifier(criterion='entropy',random_state=0) #gini or entropy
classifier.fit(X_train_scaled,y_train_scaled) 

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [340]:
y_pred = classifier.predict(X_test_scaled)
y_pred 

array([1, 0, 2, ..., 1, 1, 2])

In [341]:
train_acc = classifier.predict(X_train_scaled)
train_acc 

array([1, 0, 2, ..., 2, 1, 0])

Evaultion

In [342]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
confusion_matrix(y_pred,y_test_scaled) 

array([[236, 247, 234],
       [242, 188, 216],
       [213, 214, 210]], dtype=int64)

In [343]:
accuracy_score(y_pred,y_test_scaled) 

0.317

In [344]:
print(classification_report(y_pred,y_test_scaled)) 

              precision    recall  f1-score   support

           0       0.34      0.33      0.34       717
           1       0.29      0.29      0.29       646
           2       0.32      0.33      0.32       637

    accuracy                           0.32      2000
   macro avg       0.32      0.32      0.32      2000
weighted avg       0.32      0.32      0.32      2000



Real Data Prediction

In [345]:
classifier.predict(pd.DataFrame([[0.686567,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0]]))

array([1])

# Logistic Regression

In [346]:
from sklearn.linear_model import LogisticRegression 

In [347]:
lgr = LogisticRegression()

In [348]:
lgr.fit(X_train_scaled,y_train_scaled)

c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [349]:
y_pred = lgr.predict(X_test_scaled)
y_pred 

array([1, 0, 0, ..., 1, 2, 2])

In [350]:
train_acc = lgr.predict(X_train_scaled)
train_acc 

array([0, 0, 0, ..., 0, 0, 0])

Evaultion

In [351]:
confusion_matrix(y_pred,y_test_scaled) 

array([[349, 327, 329],
       [173, 159, 155],
       [169, 163, 176]], dtype=int64)

In [352]:
accuracy_score(y_pred,y_test_scaled) 

0.342

In [353]:
print(classification_report(y_pred,y_test_scaled)) 

              precision    recall  f1-score   support

           0       0.51      0.35      0.41      1005
           1       0.24      0.33      0.28       487
           2       0.27      0.35      0.30       508

    accuracy                           0.34      2000
   macro avg       0.34      0.34      0.33      2000
weighted avg       0.38      0.34      0.35      2000



Real Data Prediction

In [354]:
lgr.predict(pd.DataFrame([[0.686567,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0]]))

array([1])

# KNN

In [355]:
from sklearn.neighbors import KNeighborsClassifier
nc = KNeighborsClassifier(n_neighbors=3)
nc.fit(X_train_scaled,y_train_scaled) 

c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\neighbors\_classification.py:233: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=3)

In [356]:
y_pred = nc.predict(X_test_scaled)
y_pred 

array([2, 0, 0, ..., 2, 0, 2])

In [357]:
train_acc = nc.predict(X_train_scaled)
train_acc 

array([2, 0, 2, ..., 2, 1, 0])

Evaultion

In [358]:
confusion_matrix(y_pred,y_test_scaled) 

array([[346, 325, 348],
       [176, 162, 148],
       [169, 162, 164]], dtype=int64)

In [359]:
accuracy_score(y_pred,y_test_scaled) 

0.336

In [360]:
print(classification_report(y_pred,y_test_scaled)) 

              precision    recall  f1-score   support

           0       0.50      0.34      0.40      1019
           1       0.25      0.33      0.29       486
           2       0.25      0.33      0.28       495

    accuracy                           0.34      2000
   macro avg       0.33      0.33      0.32      2000
weighted avg       0.38      0.34      0.35      2000



Real Data Prediction

In [361]:
nc.predict(pd.DataFrame([[0.686567,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0]]))

array([0])

# SVC

In [362]:
from sklearn.svm import SVC
classifier_svc = SVC(kernel='linear') 
classifier_svc.fit(X_train_scaled,y_train_scaled) 

c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='linear')

In [363]:
y_pred = classifier_svc.predict(X_test_scaled)
y_pred 

array([1, 2, 0, ..., 2, 0, 0])

In [364]:
train_acc = classifier_svc.predict(X_train_scaled)
train_acc 

array([0, 0, 0, ..., 0, 0, 0])

Evaultion

In [365]:
confusion_matrix(y_pred,y_test_scaled) 

array([[461, 492, 471],
       [155,  99, 122],
       [ 75,  58,  67]], dtype=int64)

In [366]:
accuracy_score(y_pred,y_test_scaled) 

0.3135

In [367]:
print(classification_report(y_pred,y_test_scaled)) 

              precision    recall  f1-score   support

           0       0.67      0.32      0.44      1424
           1       0.15      0.26      0.19       376
           2       0.10      0.34      0.16       200

    accuracy                           0.31      2000
   macro avg       0.31      0.31      0.26      2000
weighted avg       0.51      0.31      0.36      2000



Real Data Prediction

In [368]:
classifier_svc.predict(pd.DataFrame([[0.686567,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0]]))

array([1])

# Naive Bayes

In [369]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(X_train_scaled,y_train_scaled) 

c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [370]:
y_pred = nb.predict(X_test_scaled)
y_pred 

array([1, 1, 1, ..., 2, 2, 2])

In [371]:
train_acc = nb.predict(X_train_scaled)
train_acc 

array([0, 0, 0, ..., 1, 2, 0])

Evaultion

In [372]:
confusion_matrix(y_pred,y_test_scaled) 

array([[212, 205, 214],
       [265, 234, 246],
       [214, 210, 200]], dtype=int64)

In [373]:
accuracy_score(y_pred,y_test_scaled) 

0.323

In [374]:
print(classification_report(y_pred,y_test_scaled)) 

              precision    recall  f1-score   support

           0       0.31      0.34      0.32       631
           1       0.36      0.31      0.34       745
           2       0.30      0.32      0.31       624

    accuracy                           0.32      2000
   macro avg       0.32      0.32      0.32      2000
weighted avg       0.33      0.32      0.32      2000



Real Data Prediction

In [375]:
nb.predict(pd.DataFrame([[0.686567,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0]]))

array([1])