# Importing Dataset

In [1]:
import pandas as pd 

In [50]:
df = pd.read_csv(r'D:\My Drive\apple_quality.csv')
df 

A_id      Size    Weight  Sweetness  Crunchiness  Juiciness  Ripeness  \
0        0 -3.970049 -2.512336   5.346330    -1.012009   1.844900  0.329840   
1        1 -1.195217 -2.839257   3.664059     1.588232   0.853286  0.867530   
2        2 -0.292024 -1.351282  -1.738429    -0.342616   2.838636 -0.038033   
3        3 -0.657196 -2.271627   1.324874    -0.097875   3.637970 -3.413761   
4        4  1.364217 -1.296612  -0.384658    -0.553006   3.030874 -1.303849   
...    ...       ...       ...        ...          ...        ...       ...   
3995  3995  0.059386 -1.067408  -3.714549     0.473052   1.697986  2.244055   
3996  3996 -0.293118  1.949253  -0.204020    -0.640196   0.024523 -1.087900   
3997  3997 -2.634515 -2.138247  -2.440461     0.657223   2.199709  4.763859   
3998  3998 -4.008004 -1.779337   2.366397    -0.200329   2.161435  0.214488   
3999  3999  0.278540 -1.715505   0.121217    -1.154075   1.266677 -0.776571   

       Acidity Quality  
0    -0.491590    good  
1    -0.722809    good  
2     2.621636     bad  
3     0.790723    good  
4     0.501984    good  
...        ...     ...  
3995  0.137784     bad  
3996  1.854235    good  
3997 -1.334611     bad  
3998 -2.229720    good  
3999  1.599796    good  

[4000 rows x 9 columns]

# Dataset Analysis

In [51]:
df.isnull().sum()

A_id           0
Size           0
Weight         0
Sweetness      0
Crunchiness    0
Juiciness      0
Ripeness       0
Acidity        0
Quality        0
dtype: int64

In [52]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   A_id         4000 non-null   int64  
 1   Size         4000 non-null   float64
 2   Weight       4000 non-null   float64
 3   Sweetness    4000 non-null   float64
 4   Crunchiness  4000 non-null   float64
 5   Juiciness    4000 non-null   float64
 6   Ripeness     4000 non-null   float64
 7   Acidity      4000 non-null   float64
 8   Quality      4000 non-null   object 
dtypes: float64(7), int64(1), object(1)
memory usage: 281.4+ KB


# Defining X & y for Training and Testing Dataset

In [53]:
X = df.drop(columns=['Quality','A_id'])
X 

Size    Weight  Sweetness  Crunchiness  Juiciness  Ripeness  \
0    -3.970049 -2.512336   5.346330    -1.012009   1.844900  0.329840   
1    -1.195217 -2.839257   3.664059     1.588232   0.853286  0.867530   
2    -0.292024 -1.351282  -1.738429    -0.342616   2.838636 -0.038033   
3    -0.657196 -2.271627   1.324874    -0.097875   3.637970 -3.413761   
4     1.364217 -1.296612  -0.384658    -0.553006   3.030874 -1.303849   
...        ...       ...        ...          ...        ...       ...   
3995  0.059386 -1.067408  -3.714549     0.473052   1.697986  2.244055   
3996 -0.293118  1.949253  -0.204020    -0.640196   0.024523 -1.087900   
3997 -2.634515 -2.138247  -2.440461     0.657223   2.199709  4.763859   
3998 -4.008004 -1.779337   2.366397    -0.200329   2.161435  0.214488   
3999  0.278540 -1.715505   0.121217    -1.154075   1.266677 -0.776571   

       Acidity  
0    -0.491590  
1    -0.722809  
2     2.621636  
3     0.790723  
4     0.501984  
...        ...  
3995  0.137784  
3996  1.854235  
3997 -1.334611  
3998 -2.229720  
3999  1.599796  

[4000 rows x 7 columns]

In [54]:
y = df[['Quality']]
y 

Quality
0       good
1       good
2        bad
3       good
4       good
...      ...
3995     bad
3996    good
3997     bad
3998    good
3999    good

[4000 rows x 1 columns]

# Data Preprocessing

In [58]:
y_scaled = y['Quality'].map({'good':1,'bad':0}) 
y_scaled = pd.DataFrame(y_scaled)
y_scaled 

Quality
0           1
1           1
2           0
3           1
4           1
...       ...
3995        0
3996        1
3997        0
3998        1
3999        1

[4000 rows x 1 columns]

# Split Dataset into Training & Testing 

In [59]:
from sklearn.model_selection import train_test_split 

In [64]:
X_train, X_test, y_train, y_test = train_test_split(X,y_scaled,test_size=0.2,random_state=0) 

# Multiple Linear Regression 

In [65]:
from sklearn.linear_model import LinearRegression 

In [66]:
lr = LinearRegression() 

In [67]:
model = lr.fit(X_train,y_train) 

In [68]:
y_pred = lr.predict(X_test)
y_pred  

array([[ 8.39258130e-02],
       [ 5.67359030e-01],
       [ 8.34481270e-01],
       [ 4.96856593e-01],
       [ 6.55325197e-01],
       [ 8.83218362e-01],
       [ 8.23429008e-01],
       [ 4.99089844e-02],
       [ 4.00306761e-01],
       [ 5.75799077e-01],
       [ 7.93333433e-01],
       [ 6.98622680e-01],
       [-6.86917551e-04],
       [-2.65585857e-02],
       [ 4.83082359e-01],
       [-4.53057656e-03],
       [-7.63855281e-02],
       [ 1.95125483e-01],
       [ 4.38492593e-01],
       [ 7.38907819e-01],
       [ 6.54864039e-01],
       [ 2.03834060e-01],
       [-1.78572377e-01],
       [ 3.07013674e-01],
       [ 8.00073339e-01],
       [ 4.66703660e-01],
       [ 7.84309136e-01],
       [ 3.15733547e-02],
       [ 1.26100068e-01],
       [-2.58179205e-01],
       [ 8.00713581e-01],
       [ 9.97062902e-01],
       [ 5.03099867e-01],
       [ 5.87441810e-01],
       [ 7.36586016e-01],
       [ 3.83687713e-01],
       [ 4.76189710e-01],
       [ 2.29673951e-01],
       [ 4.1

In [69]:
train_acc = lr.predict(X_train)
train_acc 

array([[0.67674321],
       [0.41629853],
       [0.27665323],
       ...,
       [0.23563647],
       [0.3586579 ],
       [0.93447641]])

Evaultion

In [70]:
from sklearn.metrics import r2_score,mean_squared_error
import numpy as np  

In [71]:
print('R2_Score: ',r2_score(y_test,y_pred))
print('MSE: ',np.sqrt(mean_squared_error(y_test,y_pred))) 

R2_Score:  0.2975933619108847
MSE:  0.4184142259797388


Real Data Prediction

In [72]:
lr.predict(pd.DataFrame([[-3.970049,-2.512336,5.346330,-1.012009,1.844900,0.329840,-0.491590]])) 

c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[0.74617562]])

# Polinomial Regression

In [73]:
from sklearn.preprocessing import PolynomialFeatures 

In [74]:
poly = PolynomialFeatures(degree=2)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.fit_transform(X_test) 

In [75]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
model = lr.fit(X_train_poly,y_train) 

In [76]:
y_pred =lr.predict(X_test_poly)
y_pred 

array([[ 0.18851147],
       [ 0.74587279],
       [ 0.86966437],
       [ 0.44943474],
       [ 0.4659028 ],
       [ 1.41009301],
       [ 0.77956426],
       [ 0.09764597],
       [ 0.4511712 ],
       [ 0.5624833 ],
       [ 0.16137231],
       [ 0.65769116],
       [ 0.1031756 ],
       [-0.42206448],
       [-0.03564389],
       [-0.07237279],
       [-0.07577743],
       [ 0.16689746],
       [ 0.78774106],
       [ 0.94007663],
       [ 0.60161227],
       [ 0.2126569 ],
       [-0.22946843],
       [ 0.56761454],
       [ 1.28787169],
       [ 0.11853395],
       [ 0.57427815],
       [ 0.21308314],
       [ 0.06676173],
       [-0.23959776],
       [ 0.95892505],
       [ 1.12695547],
       [ 0.56613682],
       [ 0.66251698],
       [ 0.65082582],
       [ 0.42458431],
       [ 0.49400994],
       [ 0.00913318],
       [ 0.38310536],
       [ 0.67927097],
       [ 0.43698981],
       [ 0.08098066],
       [ 0.59210199],
       [ 0.46200792],
       [-0.09140669],
       [ 0

In [77]:
train_acc = lr.predict(X_train_poly)
train_acc 

array([[0.54543207],
       [0.3806251 ],
       [0.32403385],
       ...,
       [0.28044244],
       [0.95156711],
       [0.75371122]])

Evaultion

In [78]:
from sklearn.metrics import r2_score,mean_squared_error

In [79]:
print('R2_Score: ',r2_score(y_test,y_pred))
print('MSE: ',np.sqrt(mean_squared_error(y_test,y_pred))) 

R2_Score:  0.4653918855360333
MSE:  0.3650311373423209


Real Data Prediction

In [80]:
lr.predict(poly.transform([[-3.970049,-2.512336,5.346330,-1.012009,1.844900,0.329840,-0.491590]]))

c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but PolynomialFeatures was fitted with feature names
  warnings.warn(


array([[1.03966067]])

# RIDGE

In [81]:
from sklearn.linear_model import Ridge
r=Ridge(alpha=0.0001) 

In [82]:
r.fit(X_train,y_train)

Ridge(alpha=0.0001)

In [83]:
y_pred = r.predict(X_test) 
y_pred 

array([[ 8.39258197e-02],
       [ 5.67359025e-01],
       [ 8.34481262e-01],
       [ 4.96856595e-01],
       [ 6.55325197e-01],
       [ 8.83218356e-01],
       [ 8.23429009e-01],
       [ 4.99089900e-02],
       [ 4.00306762e-01],
       [ 5.75799079e-01],
       [ 7.93333431e-01],
       [ 6.98622680e-01],
       [-6.86911083e-04],
       [-2.65585760e-02],
       [ 4.83082361e-01],
       [-4.53057155e-03],
       [-7.63855220e-02],
       [ 1.95125486e-01],
       [ 4.38492597e-01],
       [ 7.38907814e-01],
       [ 6.54864035e-01],
       [ 2.03834063e-01],
       [-1.78572369e-01],
       [ 3.07013676e-01],
       [ 8.00073331e-01],
       [ 4.66703663e-01],
       [ 7.84309130e-01],
       [ 3.15733621e-02],
       [ 1.26100071e-01],
       [-2.58179194e-01],
       [ 8.00713576e-01],
       [ 9.97062895e-01],
       [ 5.03099870e-01],
       [ 5.87441813e-01],
       [ 7.36586015e-01],
       [ 3.83687715e-01],
       [ 4.76189716e-01],
       [ 2.29673956e-01],
       [ 4.1

In [84]:
train_acc = r.predict(X_train)
train_acc 

array([[0.67674321],
       [0.41629854],
       [0.27665324],
       ...,
       [0.23563647],
       [0.3586579 ],
       [0.93447641]])

Evaultion

In [85]:
print('R2_Score: ',r2_score(y_test,y_pred))
print('MSE: ',np.sqrt(mean_squared_error(y_test,y_pred))) 

R2_Score:  0.29759336178221574
MSE:  0.41841422601806205


Real Data Prediction

In [86]:
r.predict(pd.DataFrame([[-3.970049,-2.512336,5.346330,-1.012009,1.844900,0.329840,-0.491590]]))

c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(


array([[0.74617562]])

# LASSO

In [87]:
from sklearn.linear_model import Lasso 
l = Lasso(alpha=0.01)

In [88]:
l.fit(X_train,y_train) 

Lasso(alpha=0.01)

In [89]:
y_pred = l.predict(X_test) 
y_pred 

array([ 0.10948409,  0.56181503,  0.79640274,  0.5138664 ,  0.65770839,
        0.85604001,  0.8248919 ,  0.07601804,  0.41382006,  0.58488022,
        0.78233443,  0.70861452,  0.02586787,  0.0142576 ,  0.48105905,
        0.00693194, -0.05590733,  0.20802026,  0.43274498,  0.72445023,
        0.62994392,  0.20484141, -0.15038694,  0.30891067,  0.77985784,
        0.47097856,  0.75693345,  0.06325353,  0.13297065, -0.21006987,
        0.7601582 ,  0.95410412,  0.51813735,  0.59884179,  0.74063725,
        0.38005574,  0.5016379 ,  0.24894196,  0.41383291,  0.80726893,
        0.38803275,  0.04442094,  0.60669009,  0.46768803, -0.04136474,
        0.71378005,  0.37084038,  0.4872509 ,  0.64179064,  0.90920594,
        0.74321992,  0.75857888,  0.58973344,  0.41267062,  1.02057611,
        0.76831808, -0.10464879,  0.11745395,  0.92114943,  0.66969049,
        0.99195225,  0.1172405 ,  0.37532582,  0.78390512,  0.22629242,
        0.84606561,  0.5879475 ,  0.35096852,  0.10211789,  0.23

In [90]:
train_acc = l.predict(X_train)
train_acc 

array([0.68170792, 0.42388557, 0.28276626, ..., 0.24664975, 0.35097289,
       0.91247006])

Evaultion

In [91]:
print('R2_Score: ',r2_score(y_test,y_pred))
print('MSE: ',np.sqrt(mean_squared_error(y_test,y_pred))) 

R2_Score:  0.2948996021707567
MSE:  0.4192157765178363


Real Data Prediction

In [92]:
l.predict(pd.DataFrame([[-3.970049,-2.512336,5.346330,-1.012009,1.844900,0.329840,-0.491590]]))

c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but Lasso was fitted with feature names
  warnings.warn(


array([0.74888078])

# Decision Tree

In [93]:
from sklearn.tree import DecisionTreeClassifier 

In [94]:
classifier = DecisionTreeClassifier(criterion='entropy',random_state=0) #gini or entropy
classifier.fit(X_train,y_train) 

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [95]:
y_pred = classifier.predict(X_test)
y_pred 

array([0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1,

In [96]:
train_acc = classifier.predict(X_train)
train_acc 

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

Evaultion

In [97]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
confusion_matrix(y_pred,y_test) 

array([[340,  76],
       [ 82, 302]], dtype=int64)

In [98]:
accuracy_score(y_pred,y_test) 

0.8025

In [99]:
print(classification_report(y_pred,y_test)) 

              precision    recall  f1-score   support

           0       0.81      0.82      0.81       416
           1       0.80      0.79      0.79       384

    accuracy                           0.80       800
   macro avg       0.80      0.80      0.80       800
weighted avg       0.80      0.80      0.80       800



Real Data Prediction

In [100]:
classifier.predict(pd.DataFrame([[-3.970049,-2.512336,5.346330,-1.012009,1.844900,0.329840,-0.491590]])) 

c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

# Logistic Regression

In [101]:
from sklearn.linear_model import LogisticRegression 

In [102]:
lgr = LogisticRegression()

In [103]:
lgr.fit(X_train,y_train)

c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [104]:
y_pred = lgr.predict(X_test)
y_pred 

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,

In [105]:
train_acc = lgr.predict(X_train)
train_acc 

array([1, 0, 0, ..., 0, 0, 1], dtype=int64)

Evaultion

In [106]:
confusion_matrix(y_pred,y_test) 

array([[310,  86],
       [112, 292]], dtype=int64)

In [107]:
accuracy_score(y_pred,y_test) 

0.7525

In [108]:
print(classification_report(y_pred,y_test)) 

              precision    recall  f1-score   support

           0       0.73      0.78      0.76       396
           1       0.77      0.72      0.75       404

    accuracy                           0.75       800
   macro avg       0.75      0.75      0.75       800
weighted avg       0.75      0.75      0.75       800



Real Data Prediction

In [109]:
lgr.predict(pd.DataFrame([[-3.970049,-2.512336,5.346330,-1.012009,1.844900,0.329840,-0.491590]])) 

c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

# KNN

In [110]:
from sklearn.neighbors import KNeighborsClassifier
nc = KNeighborsClassifier(n_neighbors=3)
nc.fit(X_train,y_train) 

c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\neighbors\_classification.py:233: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=3)

In [111]:
y_pred = nc.predict(X_test)
y_pred 

array([0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,

In [112]:
train_acc = nc.predict(X_train)
train_acc 

array([0, 0, 0, ..., 0, 1, 1], dtype=int64)

Evaultion

In [113]:
confusion_matrix(y_pred,y_test) 

array([[363,  35],
       [ 59, 343]], dtype=int64)

In [114]:
accuracy_score(y_pred,y_test) 

0.8825

In [115]:
print(classification_report(y_pred,y_test)) 

              precision    recall  f1-score   support

           0       0.86      0.91      0.89       398
           1       0.91      0.85      0.88       402

    accuracy                           0.88       800
   macro avg       0.88      0.88      0.88       800
weighted avg       0.88      0.88      0.88       800



Real Data Prediction

In [124]:
nc.predict(pd.DataFrame([[-3.970049,-2.512336,5.346330,-1.012009,1.844900,0.329840,-0.491590]])) 

c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

# SVC

In [117]:
from sklearn.svm import SVC
classifier_svc = SVC(kernel='linear') 
classifier_svc.fit(X_train,y_train) 

c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='linear')

In [118]:
y_pred = classifier_svc.predict(X_test)
y_pred 

array([0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1,

In [119]:
train_acc = classifier_svc.predict(X_train)
train_acc 

array([1, 0, 0, ..., 0, 0, 1], dtype=int64)

Evaultion

In [120]:
confusion_matrix(y_pred,y_test) 

array([[302,  81],
       [120, 297]], dtype=int64)

In [121]:
accuracy_score(y_pred,y_test) 

0.74875

In [122]:
print(classification_report(y_pred,y_test)) 

              precision    recall  f1-score   support

           0       0.72      0.79      0.75       383
           1       0.79      0.71      0.75       417

    accuracy                           0.75       800
   macro avg       0.75      0.75      0.75       800
weighted avg       0.75      0.75      0.75       800



Real Data Prediction

In [123]:
classifier_svc.predict(pd.DataFrame([[-3.970049,-2.512336,5.346330,-1.012009,1.844900,0.329840,-0.491590]])) 

c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

# Naive Bayes

In [125]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(X_train,y_train) 

c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [126]:
y_pred = nb.predict(X_test)
y_pred 

array([0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1,

In [127]:
train_acc = nb.predict(X_train)
train_acc 

array([1, 0, 0, ..., 0, 1, 1], dtype=int64)

Evaultion

In [128]:
confusion_matrix(y_pred,y_test) 

array([[308,  86],
       [114, 292]], dtype=int64)

In [129]:
accuracy_score(y_pred,y_test) 

0.75

In [130]:
print(classification_report(y_pred,y_test)) 

              precision    recall  f1-score   support

           0       0.73      0.78      0.75       394
           1       0.77      0.72      0.74       406

    accuracy                           0.75       800
   macro avg       0.75      0.75      0.75       800
weighted avg       0.75      0.75      0.75       800



Real Data Prediction

In [132]:
nb.predict(pd.DataFrame([[-3.970049,-2.512336,5.346330,-1.012009,1.844900,0.329840,-0.491590]])) 

c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


array([1], dtype=int64)