# Importing Dataset for Bengluru House Prediction

In [129]:
import pandas as pd 

In [130]:
df = pd.read_csv(r'D:\My Drive\Bengluru_House_Data.csv')
df 

area_type   availability                  location  \
0      Super built-up  Area         19-Dec  Electronic City Phase II   
1                Plot  Area  Ready To Move          Chikka Tirupathi   
2            Built-up  Area  Ready To Move               Uttarahalli   
3      Super built-up  Area  Ready To Move        Lingadheeranahalli   
4      Super built-up  Area  Ready To Move                  Kothanur   
...                     ...            ...                       ...   
13315        Built-up  Area  Ready To Move                Whitefield   
13316  Super built-up  Area  Ready To Move             Richards Town   
13317        Built-up  Area  Ready To Move     Raja Rajeshwari Nagar   
13318  Super built-up  Area         18-Jun           Padmanabhanagar   
13319  Super built-up  Area  Ready To Move              Doddathoguru   

            size  society total_sqft  bath  balcony   price  
0          2 BHK  Coomee        1056   2.0      1.0   39.07  
1      4 Bedroom  Theanmp       2600   5.0      3.0  120.00  
2          3 BHK      NaN       1440   2.0      3.0   62.00  
3          3 BHK  Soiewre       1521   3.0      1.0   95.00  
4          2 BHK      NaN       1200   2.0      1.0   51.00  
...          ...      ...        ...   ...      ...     ...  
13315  5 Bedroom  ArsiaEx       3453   4.0      0.0  231.00  
13316      4 BHK      NaN       3600   5.0      NaN  400.00  
13317      2 BHK  Mahla T       1141   2.0      1.0   60.00  
13318      4 BHK  SollyCl       4689   4.0      1.0  488.00  
13319      1 BHK      NaN        550   1.0      1.0   17.00  

[13320 rows x 9 columns]

# Dataset Analysis

we are not using area_type & society column in prediction because these two columns are covered by location in one column and for house prediction availability not matters so we are not using availability column also for house prediction.

In [131]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   area_type     13320 non-null  object 
 1   availability  13320 non-null  object 
 2   location      13319 non-null  object 
 3   size          13304 non-null  object 
 4   society       7818 non-null   object 
 5   total_sqft    13320 non-null  object 
 6   bath          13247 non-null  float64
 7   balcony       12711 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB


In [132]:
df.describe()

bath       balcony         price
count  13247.000000  12711.000000  13320.000000
mean       2.692610      1.584376    112.565627
std        1.341458      0.817263    148.971674
min        1.000000      0.000000      8.000000
25%        2.000000      1.000000     50.000000
50%        2.000000      2.000000     72.000000
75%        3.000000      2.000000    120.000000
max       40.000000      3.000000   3600.000000

In [133]:
for column in df.columns:
    print(df[column].value_counts())
    print('-'*50)

Super built-up  Area    8790
Built-up  Area          2418
Plot  Area              2025
Carpet  Area              87
Name: area_type, dtype: int64
--------------------------------------------------
Ready To Move    10581
18-Dec             307
18-May             295
18-Apr             271
18-Aug             200
                 ...  
15-Aug               1
17-Jan               1
16-Nov               1
16-Jan               1
14-Jul               1
Name: availability, Length: 81, dtype: int64
--------------------------------------------------
Whitefield                        540
Sarjapur  Road                    399
Electronic City                   302
Kanakpura Road                    273
Thanisandra                       234
                                 ... 
Bapuji Layout                       1
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
singapura paradise                  1
Abshot Layout                       1
Name: location, Length: 1305, dtype:

In [134]:
df.isnull().sum()

area_type          0
availability       0
location           1
size              16
society         5502
total_sqft         0
bath              73
balcony          609
price              0
dtype: int64

# Filling Null Values

In [135]:
df['location'].value_counts()

Whitefield                        540
Sarjapur  Road                    399
Electronic City                   302
Kanakpura Road                    273
Thanisandra                       234
                                 ... 
Bapuji Layout                       1
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
singapura paradise                  1
Abshot Layout                       1
Name: location, Length: 1305, dtype: int64

In [136]:
df['location'] = df['location'].fillna('Sarjapur  Road')
df['location'].value_counts()

Whitefield                        540
Sarjapur  Road                    400
Electronic City                   302
Kanakpura Road                    273
Thanisandra                       234
                                 ... 
Bapuji Layout                       1
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
singapura paradise                  1
Abshot Layout                       1
Name: location, Length: 1305, dtype: int64

In [137]:
df['size'].value_counts()

2 BHK         5199
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
11 Bedroom       2
10 BHK           2
14 BHK           1
13 BHK           1
12 Bedroom       1
27 BHK           1
43 Bedroom       1
16 BHK           1
19 BHK           1
18 Bedroom       1
Name: size, dtype: int64

In [138]:
df['size'] = df['size'].fillna('2 BHK')
df['size'].value_counts()

2 BHK         5215
3 BHK         4310
4 Bedroom      826
4 BHK          591
3 Bedroom      547
1 BHK          538
2 Bedroom      329
5 Bedroom      297
6 Bedroom      191
1 Bedroom      105
8 Bedroom       84
7 Bedroom       83
5 BHK           59
9 Bedroom       46
6 BHK           30
7 BHK           17
1 RK            13
10 Bedroom      12
9 BHK            8
8 BHK            5
11 BHK           2
11 Bedroom       2
10 BHK           2
14 BHK           1
13 BHK           1
12 Bedroom       1
27 BHK           1
43 Bedroom       1
16 BHK           1
19 BHK           1
18 Bedroom       1
Name: size, dtype: int64

In [139]:
df['bath'].value_counts()

2.0     6908
3.0     3286
4.0     1226
1.0      788
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
12.0       7
13.0       3
11.0       3
16.0       2
27.0       1
40.0       1
15.0       1
14.0       1
18.0       1
Name: bath, dtype: int64

In [140]:
df['bath'] = df['bath'].fillna(df['bath'].median())
df['bath'].value_counts()

2.0     6981
3.0     3286
4.0     1226
1.0      788
5.0      524
6.0      273
7.0      102
8.0       64
9.0       43
10.0      13
12.0       7
13.0       3
11.0       3
16.0       2
27.0       1
40.0       1
15.0       1
14.0       1
18.0       1
Name: bath, dtype: int64

In [141]:
df['balcony'].value_counts()

2.0    5113
1.0    4897
3.0    1672
0.0    1029
Name: balcony, dtype: int64

In [142]:
df['balcony'] = df['balcony'].fillna(df['balcony'].median())
df['balcony'].value_counts()

2.0    5722
1.0    4897
3.0    1672
0.0    1029
Name: balcony, dtype: int64

In [143]:
df.isnull().sum() 

area_type          0
availability       0
location           0
size               0
society         5502
total_sqft         0
bath               0
balcony            0
price              0
dtype: int64

# Data Cleaning

In [144]:
df.info() 

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13320 entries, 0 to 13319
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   area_type     13320 non-null  object 
 1   availability  13320 non-null  object 
 2   location      13320 non-null  object 
 3   size          13320 non-null  object 
 4   society       7818 non-null   object 
 5   total_sqft    13320 non-null  object 
 6   bath          13320 non-null  float64
 7   balcony       13320 non-null  float64
 8   price         13320 non-null  float64
dtypes: float64(3), object(6)
memory usage: 936.7+ KB


Fixing House Size

In [145]:
df['bhk'] = df['size'].str.split().str.get(0).astype('int')
df 

area_type   availability                  location  \
0      Super built-up  Area         19-Dec  Electronic City Phase II   
1                Plot  Area  Ready To Move          Chikka Tirupathi   
2            Built-up  Area  Ready To Move               Uttarahalli   
3      Super built-up  Area  Ready To Move        Lingadheeranahalli   
4      Super built-up  Area  Ready To Move                  Kothanur   
...                     ...            ...                       ...   
13315        Built-up  Area  Ready To Move                Whitefield   
13316  Super built-up  Area  Ready To Move             Richards Town   
13317        Built-up  Area  Ready To Move     Raja Rajeshwari Nagar   
13318  Super built-up  Area         18-Jun           Padmanabhanagar   
13319  Super built-up  Area  Ready To Move              Doddathoguru   

            size  society total_sqft  bath  balcony   price  bhk  
0          2 BHK  Coomee        1056   2.0      1.0   39.07    2  
1      4 Bedroom  Theanmp       2600   5.0      3.0  120.00    4  
2          3 BHK      NaN       1440   2.0      3.0   62.00    3  
3          3 BHK  Soiewre       1521   3.0      1.0   95.00    3  
4          2 BHK      NaN       1200   2.0      1.0   51.00    2  
...          ...      ...        ...   ...      ...     ...  ...  
13315  5 Bedroom  ArsiaEx       3453   4.0      0.0  231.00    5  
13316      4 BHK      NaN       3600   5.0      2.0  400.00    4  
13317      2 BHK  Mahla T       1141   2.0      1.0   60.00    2  
13318      4 BHK  SollyCl       4689   4.0      1.0  488.00    4  
13319      1 BHK      NaN        550   1.0      1.0   17.00    1  

[13320 rows x 10 columns]

In [146]:
df[df.bhk > 20]

area_type   availability                   location  \
1718  Super built-up  Area  Ready To Move  2Electronic City Phase II   
4684            Plot  Area  Ready To Move                Munnekollal   

            size society total_sqft  bath  balcony  price  bhk  
1718      27 BHK     NaN       8000  27.0      0.0  230.0   27  
4684  43 Bedroom     NaN       2400  40.0      0.0  660.0   43

Fixing House Square Fit

In [147]:
df['total_sqft'].unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      dtype=object)

In [148]:
def convert(x):
    temp = x.split('-')
    if len(temp) == 2:
        return (float(temp[0]) + float(temp[1])) / 2
    try:
        return float(x)
    except:
        return None

In [149]:
df['total_sqft'] = df['total_sqft'].apply(convert) 

In [150]:
df

area_type   availability                  location  \
0      Super built-up  Area         19-Dec  Electronic City Phase II   
1                Plot  Area  Ready To Move          Chikka Tirupathi   
2            Built-up  Area  Ready To Move               Uttarahalli   
3      Super built-up  Area  Ready To Move        Lingadheeranahalli   
4      Super built-up  Area  Ready To Move                  Kothanur   
...                     ...            ...                       ...   
13315        Built-up  Area  Ready To Move                Whitefield   
13316  Super built-up  Area  Ready To Move             Richards Town   
13317        Built-up  Area  Ready To Move     Raja Rajeshwari Nagar   
13318  Super built-up  Area         18-Jun           Padmanabhanagar   
13319  Super built-up  Area  Ready To Move              Doddathoguru   

            size  society  total_sqft  bath  balcony   price  bhk  
0          2 BHK  Coomee       1056.0   2.0      1.0   39.07    2  
1      4 Bedroom  Theanmp      2600.0   5.0      3.0  120.00    4  
2          3 BHK      NaN      1440.0   2.0      3.0   62.00    3  
3          3 BHK  Soiewre      1521.0   3.0      1.0   95.00    3  
4          2 BHK      NaN      1200.0   2.0      1.0   51.00    2  
...          ...      ...         ...   ...      ...     ...  ...  
13315  5 Bedroom  ArsiaEx      3453.0   4.0      0.0  231.00    5  
13316      4 BHK      NaN      3600.0   5.0      2.0  400.00    4  
13317      2 BHK  Mahla T      1141.0   2.0      1.0   60.00    2  
13318      4 BHK  SollyCl      4689.0   4.0      1.0  488.00    4  
13319      1 BHK      NaN       550.0   1.0      1.0   17.00    1  

[13320 rows x 10 columns]

Finding Price Per Square Fit (Removing Outliers)

In [151]:
df['price_per_sqft'] = df['price']*100000/df['total_sqft'] 

In [152]:
df['price_per_sqft'] 

0         3699.810606
1         4615.384615
2         4305.555556
3         6245.890861
4         4250.000000
             ...     
13315     6689.834926
13316    11111.111111
13317     5258.545136
13318    10407.336319
13319     3090.909091
Name: price_per_sqft, Length: 13320, dtype: float64

In [153]:
df.describe()

total_sqft          bath       balcony         price           bhk  \
count  13274.000000  13320.000000  13320.000000  13320.000000  13320.000000   
mean    1559.626694      2.688814      1.603378    112.565627      2.802778   
std     1238.405258      1.338754      0.803067    148.971674      1.294496   
min        1.000000      1.000000      0.000000      8.000000      1.000000   
25%     1100.000000      2.000000      1.000000     50.000000      2.000000   
50%     1276.000000      2.000000      2.000000     72.000000      3.000000   
75%     1680.000000      3.000000      2.000000    120.000000      3.000000   
max    52272.000000     40.000000      3.000000   3600.000000     43.000000   

       price_per_sqft  
count    1.327400e+04  
mean     7.907501e+03  
std      1.064296e+05  
min      2.678298e+02  
25%      4.266865e+03  
50%      5.434306e+03  
75%      7.311746e+03  
max      1.200000e+07

Fixing House Location

In [154]:
df['location'].value_counts() 

Whitefield                        540
Sarjapur  Road                    400
Electronic City                   302
Kanakpura Road                    273
Thanisandra                       234
                                 ... 
Bapuji Layout                       1
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
singapura paradise                  1
Abshot Layout                       1
Name: location, Length: 1305, dtype: int64

In [155]:
df['location'] = df['location'].apply(lambda x:x.strip()) # Using strip we are removing null space in location column

In [156]:
location_count = df['location'].value_counts()
location_count 

Whitefield                        541
Sarjapur  Road                    400
Electronic City                   304
Kanakpura Road                    273
Thanisandra                       237
                                 ... 
Bapuji Layout                       1
1st Stage Radha Krishna Layout      1
BEML Layout 5th stage               1
singapura paradise                  1
Abshot Layout                       1
Name: location, Length: 1294, dtype: int64

In [157]:
location_count_less_10 = location_count[location_count<=10]
location_count_less_10 

Dairy Circle                      10
Nagappa Reddy Layout              10
Basapura                          10
1st Block Koramangala             10
Sector 1 HSR Layout               10
                                  ..
Bapuji Layout                      1
1st Stage Radha Krishna Layout     1
BEML Layout 5th stage              1
singapura paradise                 1
Abshot Layout                      1
Name: location, Length: 1053, dtype: int64

In [158]:
df['location'] = df['location'].apply(lambda x:'other' if x in location_count_less_10 else x) 

In [159]:
df['location'].value_counts()

other                 2885
Whitefield             541
Sarjapur  Road         400
Electronic City        304
Kanakpura Road         273
                      ... 
Nehru Nagar             11
Banjara Layout          11
LB Shastri Nagar        11
Pattandur Agrahara      11
Narayanapura            11
Name: location, Length: 242, dtype: int64

Outlier Handle

In [160]:
df.describe()

total_sqft          bath       balcony         price           bhk  \
count  13274.000000  13320.000000  13320.000000  13320.000000  13320.000000   
mean    1559.626694      2.688814      1.603378    112.565627      2.802778   
std     1238.405258      1.338754      0.803067    148.971674      1.294496   
min        1.000000      1.000000      0.000000      8.000000      1.000000   
25%     1100.000000      2.000000      1.000000     50.000000      2.000000   
50%     1276.000000      2.000000      2.000000     72.000000      3.000000   
75%     1680.000000      3.000000      2.000000    120.000000      3.000000   
max    52272.000000     40.000000      3.000000   3600.000000     43.000000   

       price_per_sqft  
count    1.327400e+04  
mean     7.907501e+03  
std      1.064296e+05  
min      2.678298e+02  
25%      4.266865e+03  
50%      5.434306e+03  
75%      7.311746e+03  
max      1.200000e+07

In [161]:
df = df[((df['total_sqft']/df['bhk']) >= 300)] 
df.describe()

total_sqft          bath       balcony         price           bhk  \
count  12530.000000  12530.000000  12530.000000  12530.000000  12530.000000   
mean    1594.564544      2.559537      1.604629    111.382401      2.650838   
std     1261.271296      1.077938      0.796238    152.077329      0.976678   
min      300.000000      1.000000      0.000000      8.440000      1.000000   
25%     1116.000000      2.000000      1.000000     49.000000      2.000000   
50%     1300.000000      2.000000      2.000000     70.000000      3.000000   
75%     1700.000000      3.000000      2.000000    115.000000      3.000000   
max    52272.000000     16.000000      3.000000   3600.000000     16.000000   

       price_per_sqft  
count    12530.000000  
mean      6303.979357  
std       4162.237981  
min        267.829813  
25%       4210.526316  
50%       5294.117647  
75%       6916.666667  
max     176470.588235

In [162]:
upper_limit = df['price_per_sqft'].quantile(0.99)
upper_limit 

21707.94263651399

In [163]:
lower_limit = df['price_per_sqft'].quantile(0.01)
lower_limit 

2500.362544795758

In [164]:
df = df[(df['price_per_sqft']<=21707.94) & (df['price_per_sqft']>=2500.36)]
df.describe()

total_sqft          bath       balcony         price           bhk  \
count  12279.000000  12279.000000  12279.000000  12279.000000  12279.000000   
mean    1561.545008      2.546380      1.606157    104.415149      2.639466   
std      947.007069      1.050265      0.795275    115.124890      0.954107   
min      300.000000      1.000000      0.000000     10.000000      1.000000   
25%     1116.000000      2.000000      1.000000     49.500000      2.000000   
50%     1300.000000      2.000000      2.000000     70.000000      3.000000   
75%     1697.000000      3.000000      2.000000    115.000000      3.000000   
max    30400.000000     16.000000      3.000000   2200.000000     16.000000   

       price_per_sqft  
count    12279.000000  
mean      6099.750797  
std       2968.038286  
min       2500.361011  
25%       4237.288136  
50%       5294.117647  
75%       6863.905325  
max      21649.200221

In [165]:
df

area_type   availability                  location  \
0      Super built-up  Area         19-Dec  Electronic City Phase II   
1                Plot  Area  Ready To Move          Chikka Tirupathi   
2            Built-up  Area  Ready To Move               Uttarahalli   
3      Super built-up  Area  Ready To Move        Lingadheeranahalli   
4      Super built-up  Area  Ready To Move                  Kothanur   
...                     ...            ...                       ...   
13315        Built-up  Area  Ready To Move                Whitefield   
13316  Super built-up  Area  Ready To Move                     other   
13317        Built-up  Area  Ready To Move     Raja Rajeshwari Nagar   
13318  Super built-up  Area         18-Jun           Padmanabhanagar   
13319  Super built-up  Area  Ready To Move              Doddathoguru   

            size  society  total_sqft  bath  balcony   price  bhk  \
0          2 BHK  Coomee       1056.0   2.0      1.0   39.07    2   
1      4 Bedroom  Theanmp      2600.0   5.0      3.0  120.00    4   
2          3 BHK      NaN      1440.0   2.0      3.0   62.00    3   
3          3 BHK  Soiewre      1521.0   3.0      1.0   95.00    3   
4          2 BHK      NaN      1200.0   2.0      1.0   51.00    2   
...          ...      ...         ...   ...      ...     ...  ...   
13315  5 Bedroom  ArsiaEx      3453.0   4.0      0.0  231.00    5   
13316      4 BHK      NaN      3600.0   5.0      2.0  400.00    4   
13317      2 BHK  Mahla T      1141.0   2.0      1.0   60.00    2   
13318      4 BHK  SollyCl      4689.0   4.0      1.0  488.00    4   
13319      1 BHK      NaN       550.0   1.0      1.0   17.00    1   

       price_per_sqft  
0         3699.810606  
1         4615.384615  
2         4305.555556  
3         6245.890861  
4         4250.000000  
...               ...  
13315     6689.834926  
13316    11111.111111  
13317     5258.545136  
13318    10407.336319  
13319     3090.909091  

[12279 rows x 11 columns]

In [166]:
df.drop(columns=['area_type','availability','size','society','price_per_sqft'],inplace=True) 

# Getting Cleaned Dataset

In [167]:
df

location  total_sqft  bath  balcony   price  bhk
0      Electronic City Phase II      1056.0   2.0      1.0   39.07    2
1              Chikka Tirupathi      2600.0   5.0      3.0  120.00    4
2                   Uttarahalli      1440.0   2.0      3.0   62.00    3
3            Lingadheeranahalli      1521.0   3.0      1.0   95.00    3
4                      Kothanur      1200.0   2.0      1.0   51.00    2
...                         ...         ...   ...      ...     ...  ...
13315                Whitefield      3453.0   4.0      0.0  231.00    5
13316                     other      3600.0   5.0      2.0  400.00    4
13317     Raja Rajeshwari Nagar      1141.0   2.0      1.0   60.00    2
13318           Padmanabhanagar      4689.0   4.0      1.0  488.00    4
13319              Doddathoguru       550.0   1.0      1.0   17.00    1

[12279 rows x 6 columns]

# Convert dataset to csv file

In [168]:
df.to_csv('New_Bengluru_House_Data.csv') 

# Check df info

In [169]:
df.isnull().sum()

location      0
total_sqft    0
bath          0
balcony       0
price         0
bhk           0
dtype: int64

In [170]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12279 entries, 0 to 13319
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   location    12279 non-null  object 
 1   total_sqft  12279 non-null  float64
 2   bath        12279 non-null  float64
 3   balcony     12279 non-null  float64
 4   price       12279 non-null  float64
 5   bhk         12279 non-null  int32  
dtypes: float64(4), int32(1), object(1)
memory usage: 623.5+ KB


# Defining X & y for Training and Testing Dataset

In [171]:
X = df.drop(columns='price')
X 

location  total_sqft  bath  balcony  bhk
0      Electronic City Phase II      1056.0   2.0      1.0    2
1              Chikka Tirupathi      2600.0   5.0      3.0    4
2                   Uttarahalli      1440.0   2.0      3.0    3
3            Lingadheeranahalli      1521.0   3.0      1.0    3
4                      Kothanur      1200.0   2.0      1.0    2
...                         ...         ...   ...      ...  ...
13315                Whitefield      3453.0   4.0      0.0    5
13316                     other      3600.0   5.0      2.0    4
13317     Raja Rajeshwari Nagar      1141.0   2.0      1.0    2
13318           Padmanabhanagar      4689.0   4.0      1.0    4
13319              Doddathoguru       550.0   1.0      1.0    1

[12279 rows x 5 columns]

In [172]:
y = df[['price']]
y

price
0       39.07
1      120.00
2       62.00
3       95.00
4       51.00
...       ...
13315  231.00
13316  400.00
13317   60.00
13318  488.00
13319   17.00

[12279 rows x 1 columns]

# Split Dataset into Training & Testing

In [173]:
from sklearn.model_selection import train_test_split

In [174]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0)

# Data Preprocessing

In [175]:
from sklearn.compose import make_column_transformer 
from sklearn.preprocessing import OneHotEncoder,StandardScaler 

In [176]:
ct = make_column_transformer((OneHotEncoder(sparse=False),['location']),remainder='passthrough') 
ct 

ColumnTransformer(remainder='passthrough',
                  transformers=[('onehotencoder', OneHotEncoder(sparse=False),
                                 ['location'])])

In [177]:
sc = StandardScaler()
sc 

StandardScaler()

# Multiple Linear Regression

In [178]:
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import make_pipeline 

In [179]:
lr = LinearRegression()
lr 

LinearRegression()

In [180]:
pipe = make_pipeline(ct,sc,lr)
pipe 

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()),
                ('linearregression', LinearRegression())])

In [181]:
model = pipe.fit(X_train,y_train)
model 

c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()),
                ('linearregression', LinearRegression())])

# Prediction

In [182]:
y_pred = pipe.predict(X_test)
y_pred 

array([[ 78.24178992],
       [119.59620679],
       [ 31.56299567],
       ...,
       [ 94.45776887],
       [ 79.12444379],
       [-18.30044422]])

In [183]:
train_acc = pipe.predict(X_train)
train_acc 

array([[ 88.3949516 ],
       [ 24.11206574],
       [ 86.46972957],
       ...,
       [232.92497433],
       [ 24.42237067],
       [ 52.84823523]])

# Evaulton

In [184]:
from sklearn.metrics import r2_score,mean_squared_error
import numpy as np 

In [185]:
print('R2_Score: ',r2_score(y_test,y_pred))
print('MSE: ',np.sqrt(mean_squared_error(y_test,y_pred))) 

R2_Score:  0.7141148828617261
MSE:  63.159673485337336


In [186]:
print('R2_Score: ',r2_score(y_train,train_acc))
print('MSE: ',np.sqrt(mean_squared_error(y_train,train_acc))) 

R2_Score:  0.7286223076585833
MSE:  59.57091269574407


# Real Data Prediction

In [187]:
pipe.predict(pd.DataFrame([['other',3600,5,2,4]],columns=['location','total_sqft','bath','balcony','bhk']))

array([[325.85301682]])

In [188]:
pipe.predict(pd.DataFrame([['Kothanur',3639,3,2,3]],columns=['location','total_sqft','bath','balcony','bhk']))

array([[283.40869886]])

# Apply Lasso

In [196]:
from sklearn.linear_model import Lasso

In [197]:
ls = Lasso()
pipe = make_pipeline(ct,sc,ls)
pipe.fit(X_train,y_train)

c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()), ('lasso', Lasso())])

In [198]:
y_pred_ls = pipe.predict(X_test)
print('R2_Score: ',r2_score(y_test,y_pred_ls))
print('MSE: ',np.sqrt(mean_squared_error(y_test,y_pred_ls))) 

R2_Score:  0.7164527394118834
MSE:  62.90089581383814


In [199]:
pipe.predict(pd.DataFrame([['other',3600,5,2,4]],columns=['location','total_sqft','bath','balcony','bhk']))

array([317.66213956])

In [200]:
pipe.predict(pd.DataFrame([['Kothanur',3639,3,2,3]],columns=['location','total_sqft','bath','balcony','bhk']))

array([296.58393295])

# Apply Ridge

In [201]:
from sklearn.linear_model import Ridge

In [202]:
rg = Ridge()
pipe = make_pipeline(ct,sc,rg)
pipe.fit(X_train,y_train)

c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\preprocessing\_encoders.py:975: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse=False),
                                                  ['location'])])),
                ('standardscaler', StandardScaler()), ('ridge', Ridge())])

In [203]:
y_pred_rg = pipe.predict(X_test)
print('R2_Score: ',r2_score(y_test,y_pred_rg))
print('MSE: ',np.sqrt(mean_squared_error(y_test,y_pred_rg))) 

R2_Score:  0.7141591885981053
MSE:  63.154779134243846


In [204]:
pipe.predict(pd.DataFrame([['other',3600,5,2,4]],columns=['location','total_sqft','bath','balcony','bhk']))

array([[325.88989117]])

In [205]:
pipe.predict(pd.DataFrame([['Kothanur',3639,3,2,3]],columns=['location','total_sqft','bath','balcony','bhk']))

array([[283.12703143]])

# Different R2_Score

In [206]:
print('R2_Score with No Regularization: ',r2_score(y_test,y_pred))
print('R2_Score with Lasso: ',r2_score(y_test,y_pred_ls))
print('R2_Score with Ridge: ',r2_score(y_test,y_pred_rg)) 

R2_Score with No Regularization:  0.7141148828617261
R2_Score with Lasso:  0.7164527394118834
R2_Score with Ridge:  0.7141591885981053


# Save Model

In [207]:
import pickle

In [208]:
pickle.dump(pipe,open('RidgeModel.pkl','wb'))