# Importing Dataset

In [7]:
import pandas as pd

In [8]:
df = pd.read_csv(r'D:\My Drive\Corona_NLP_test.csv')
df 

UserName  ScreenName             Location     TweetAt  \
0            1       44953                  NYC  02-03-2020   
1            2       44954          Seattle, WA  02-03-2020   
2            3       44955                  NaN  02-03-2020   
3            4       44956          Chicagoland  02-03-2020   
4            5       44957  Melbourne, Victoria  03-03-2020   
...        ...         ...                  ...         ...   
3793      3794       48746            Israel ??  16-03-2020   
3794      3795       48747       Farmington, NM  16-03-2020   
3795      3796       48748        Haverford, PA  16-03-2020   
3796      3797       48749                  NaN  16-03-2020   
3797      3798       48750  Arlington, Virginia  16-03-2020   

                                          OriginalTweet           Sentiment  
0     TRENDING: New Yorkers encounter empty supermar...  Extremely Negative  
1     When I couldn't find hand sanitizer at Fred Me...            Positive  
2     Find out how you can protect yourself and love...  Extremely Positive  
3     #Panic buying hits #NewYork City as anxious sh...            Negative  
4     #toiletpaper #dunnypaper #coronavirus #coronav...             Neutral  
...                                                 ...                 ...  
3793  Meanwhile In A Supermarket in Israel -- People...            Positive  
3794  Did you panic buy a lot of non-perishable item...            Negative  
3795  Asst Prof of Economics @cconces was on @NBCPhi...             Neutral  
3796  Gov need to do somethings instead of biar je r...  Extremely Negative  
3797  I and @ForestandPaper members are committed to...  Extremely Positive  

[3798 rows x 6 columns]

# Cleaning Dataset

In [9]:
df.drop(columns=['UserName','ScreenName','Location','TweetAt'],inplace=True)
df 

OriginalTweet           Sentiment
0     TRENDING: New Yorkers encounter empty supermar...  Extremely Negative
1     When I couldn't find hand sanitizer at Fred Me...            Positive
2     Find out how you can protect yourself and love...  Extremely Positive
3     #Panic buying hits #NewYork City as anxious sh...            Negative
4     #toiletpaper #dunnypaper #coronavirus #coronav...             Neutral
...                                                 ...                 ...
3793  Meanwhile In A Supermarket in Israel -- People...            Positive
3794  Did you panic buy a lot of non-perishable item...            Negative
3795  Asst Prof of Economics @cconces was on @NBCPhi...             Neutral
3796  Gov need to do somethings instead of biar je r...  Extremely Negative
3797  I and @ForestandPaper members are committed to...  Extremely Positive

[3798 rows x 2 columns]

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3798 entries, 0 to 3797
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype 
---  ------         --------------  ----- 
 0   OriginalTweet  3798 non-null   object
 1   Sentiment      3798 non-null   object
dtypes: object(2)
memory usage: 59.5+ KB


In [12]:
df.isnull().sum()

OriginalTweet    0
Sentiment        0
dtype: int64

In [10]:
df.duplicated().sum()

0

In [13]:
df['Sentiment'].value_counts()

Negative              1041
Positive               947
Neutral                619
Extremely Positive     599
Extremely Negative     592
Name: Sentiment, dtype: int64

# Convert into Lower Case

In [14]:
df['OriginalTweet']=df['OriginalTweet'].str.lower()  

In [15]:
df.head()

OriginalTweet           Sentiment
0  trending: new yorkers encounter empty supermar...  Extremely Negative
1  when i couldn't find hand sanitizer at fred me...            Positive
2  find out how you can protect yourself and love...  Extremely Positive
3  #panic buying hits #newyork city as anxious sh...            Negative
4  #toiletpaper #dunnypaper #coronavirus #coronav...             Neutral

# Remove Unwanted Data like html tags

In [16]:
import re
def remove_html_tags(text):
    pattern = re.compile('<.*?>')
    return pattern.sub(r'',str(text))

In [17]:
df['OriginalTweet']=df['OriginalTweet'].apply(remove_html_tags)

In [18]:
df.head()

OriginalTweet           Sentiment
0  trending: new yorkers encounter empty supermar...  Extremely Negative
1  when i couldn't find hand sanitizer at fred me...            Positive
2  find out how you can protect yourself and love...  Extremely Positive
3  #panic buying hits #newyork city as anxious sh...            Negative
4  #toiletpaper #dunnypaper #coronavirus #coronav...             Neutral

# Remove url

In [19]:
def remove_url(text):
    pattern = re.compile(r'http?://\S+|www\.\S+')
    return pattern.sub(r'',str(text))

In [20]:
df['OriginalTweet']=df['OriginalTweet'].apply(remove_url)

In [21]:
df.head()

OriginalTweet           Sentiment
0  trending: new yorkers encounter empty supermar...  Extremely Negative
1  when i couldn't find hand sanitizer at fred me...            Positive
2  find out how you can protect yourself and love...  Extremely Positive
3  #panic buying hits #newyork city as anxious sh...            Negative
4  #toiletpaper #dunnypaper #coronavirus #coronav...             Neutral

# Remove Punctuation (!"#$%&\'()*+,-./:;<=>?@[\]^_`{|}~)

In [22]:
import string
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [23]:
exclude = string.punctuation

In [24]:
def remove_punc(text):
    return text.translate(str.maketrans('','',exclude))

In [25]:
df['OriginalTweet']=df['OriginalTweet'].apply(remove_punc)

In [26]:
df.head()

OriginalTweet           Sentiment
0  trending new yorkers encounter empty supermark...  Extremely Negative
1  when i couldnt find hand sanitizer at fred mey...            Positive
2  find out how you can protect yourself and love...  Extremely Positive
3  panic buying hits newyork city as anxious shop...            Negative
4  toiletpaper dunnypaper coronavirus coronavirus...             Neutral

# Correct Spelling for that pip install textblob (maner - manner)

In [27]:
from textblob import TextBlob

In [28]:
def correct_spelling(text):
    return TextBlob(text).correct().string      

In [29]:
df['OriginalTweet']=df['OriginalTweet'].apply(correct_spelling)

In [30]:
df

OriginalTweet           Sentiment
0     treading new yorkers encounter empty supermark...  Extremely Negative
1     when i couldn find hand sanitizer at fred meye...            Positive
2     find out how you can protect yourself and love...  Extremely Positive
3     panic buying hits network city as anxious ship...            Negative
4     toiletpaper dunnypaper coronavirus coronavirus...             Neutral
...                                                 ...                 ...
3793  meanwhile in a supermarket in israel  people d...            Positive
3794  did you panic buy a lot of nonperishable items...            Negative
3795  asset prof of economics chances was on nbcphil...             Neutral
3796  go need to do something instead of bear je rak...  Extremely Negative
3797  i and forestandpaper members are committed to ...  Extremely Positive

[3798 rows x 2 columns]

# Remove Stop Words (a, the, etc...) for that pip install nltk

In [32]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [33]:
from nltk.corpus import stopwords
stop_words = set(stopwords.words('english')) # Choose the language for stopwords 

In [34]:
def remove_stopwords(text):
   new_text = []
   for word in text.split():
      if word not in stopwords.words('english'):
         new_text.append(word)
   return" ".join(new_text) 

In [35]:
df['OriginalTweet']=df['OriginalTweet'].apply(remove_stopwords)

In [36]:
df

OriginalTweet           Sentiment
0     treading new yorkers encounter empty supermark...  Extremely Negative
1     find hand sanitizer fred meyer turned amazon 1...            Positive
2                   find protect loved ones coronavirus  Extremely Positive
3     panic buying hits network city anxious shipper...            Negative
4     toiletpaper dunnypaper coronavirus coronavirus...             Neutral
...                                                 ...                 ...
3793  meanwhile supermarket israel people dance sing...            Positive
3794  panic buy lot nonperishable items echo needs f...            Negative
3795  asset prof economics chances nbcphiladelphia t...             Neutral
3796  go need something instead bear je rakyat assum...  Extremely Negative
3797  forestandpaper members committed safety employ...  Extremely Positive

[3798 rows x 2 columns]

# Remove Emojies

In [37]:
import re
def remove_emoji(text):
    emoji_pattern = re.compile("["
                        u"\U0001F600-\U0001F64F"  # emoticons
                        u"\U0001F300-\U0001F5FF"  # symbols & pictographs
                        u"\U0001F680-\U0001F6FF"  # transport & map symbols
                        u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
                        u"\U00002500-\U00002BEF"  # chinese characters
                        u"\U00002702-\U000027B0"
                        u"\U00002702-\U000027B0"
                        u"\U000024C2-\U0001F251"
                        u"\U0001f926-\U0001f937"
                        u"\U00010000-\U0010ffff"
                        u"\u2640-\u2642"
                        u"\u2600-\u2B55"
                        u"\u200d"
                        u"\u23cf"
                        u"\u23e9"
                        u"\u231a"
                        u"\ufe0f"  # dingbats
                        u"\u3030"  
                       "]+",flags=re.UNICODE)
    return emoji_pattern.sub(r'',text)   

In [38]:
df['OriginalTweet']=df['OriginalTweet'].apply(remove_emoji)

In [39]:
df.head()

OriginalTweet           Sentiment
0  treading new yorkers encounter empty supermark...  Extremely Negative
1  find hand sanitizer fred meyer turned amazon 1...            Positive
2                find protect loved ones coronavirus  Extremely Positive
3  panic buying hits network city anxious shipper...            Negative
4  toiletpaper dunnypaper coronavirus coronavirus...             Neutral

# Stemming Words (likes, liked, likely, liking - like)

In [40]:
from nltk.stem.porter import PorterStemmer

In [41]:
ps = PorterStemmer()
def stem_words(text):
    return " ".join([ps.stem(word) for word in text.split()])

In [42]:
df['OriginalTweet']=df['OriginalTweet'].apply(stem_words)

In [43]:
df

OriginalTweet           Sentiment
0     tread new yorker encount empti supermarket she...  Extremely Negative
1     find hand sanit fred meyer turn amazon 11497 2...            Positive
2                      find protect love one coronaviru  Extremely Positive
3     panic buy hit network citi anxiou shipper stoc...            Negative
4     toiletpap dunnypap coronaviru coronavirusaustr...             Neutral
...                                                 ...                 ...
3793  meanwhil supermarket israel peopl danc sing to...            Positive
3794  panic buy lot nonperish item echo need food do...            Negative
3795  asset prof econom chanc nbcphiladelphia talk r...             Neutral
3796  go need someth instead bear je rakyat assum lo...  Extremely Negative
3797  forestandpap member commit safeti employe endu...  Extremely Positive

[3798 rows x 2 columns]

# Apply TF-IDF (Term frequency-inverse Document Frequency) Model

In [44]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [45]:
tfidf = TfidfVectorizer() 

In [46]:
bow = tfidf.fit_transform(df['OriginalTweet'])

In [47]:
bow

<3798x9971 sparse matrix of type '<class 'numpy.float64'>'
	with 70249 stored elements in Compressed Sparse Row format>

In [48]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[8.54934597 7.85619879 8.54934597 ... 8.54934597 8.54934597 8.54934597]
['00' '000' '0095' ... 'zásobi' 'zásobováni' 'zástupc']


In [49]:
print(bow[0].toarray())

[[0. 0. 0. ... 0. 0. 0.]]


In [51]:
matrix = tfidf.fit_transform(df['OriginalTweet']).toarray()
matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

# Preprocessing

In [52]:
from sklearn.preprocessing import LabelEncoder

In [53]:
le = LabelEncoder()

In [54]:
df['Sentiment'] = le.fit_transform(df['Sentiment'])

In [111]:
df

OriginalTweet  Sentiment
0     tread new yorker encount empti supermarket she...          0
1     find hand sanit fred meyer turn amazon 11497 2...          4
2                      find protect love one coronaviru          1
3     panic buy hit network citi anxiou shipper stoc...          2
4     toiletpap dunnypap coronaviru coronavirusaustr...          3
...                                                 ...        ...
3793  meanwhil supermarket israel peopl danc sing to...          4
3794  panic buy lot nonperish item echo need food do...          2
3795  asset prof econom chanc nbcphiladelphia talk r...          3
3796  go need someth instead bear je rakyat assum lo...          0
3797  forestandpap member commit safeti employe endu...          1

[3798 rows x 2 columns]

# Defining X & y for Training and Testing Dataset

In [56]:
X = matrix
y = df[['Sentiment']]

# Split Dataset into Training & Testing

In [57]:
from sklearn.model_selection import train_test_split 

In [58]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=0) 

# Linear Regression

In [59]:
from sklearn.linear_model import LinearRegression 

In [60]:
lr = LinearRegression() 

In [61]:
model = lr.fit(X_train,y_train) 

In [62]:
y_pred = lr.predict(X_test)

In [63]:
from sklearn.metrics import r2_score

In [64]:
print('R2_Score: ',r2_score(y_test,y_pred))

R2_Score:  -0.3177652859230333


# RIDGE

In [65]:
from sklearn.linear_model import Ridge

In [66]:
r=Ridge(alpha=0.0001) 

In [67]:
r.fit(X_train,y_train)

Ridge(alpha=0.0001)

In [68]:
y_pred = r.predict(X_test) 

In [69]:
print('R2_Score: ',r2_score(y_test,y_pred))

R2_Score:  -0.31650975215405164


# LASSO

In [70]:
from sklearn.linear_model import Lasso 

In [71]:
l = Lasso(alpha=0.01)

In [72]:
l.fit(X_train,y_train) 

Lasso(alpha=0.01)

In [73]:
y_pred = l.predict(X_test) 

In [74]:
print('R2_Score: ',r2_score(y_test,y_pred))

R2_Score:  0.0103906824970732


# Decision Tree

In [75]:
from sklearn.tree import DecisionTreeClassifier 

In [76]:
classifier = DecisionTreeClassifier(criterion='entropy',random_state=0)

In [77]:
classifier.fit(X_train,y_train) 

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [78]:
y_pred = classifier.predict(X_test)

In [79]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report

In [80]:
confusion_matrix(y_pred,y_test) 

array([[32, 10, 32,  5, 28],
       [ 9, 49, 14,  8, 33],
       [43, 22, 72, 37, 55],
       [14,  7, 28, 42, 24],
       [26, 32, 45, 33, 60]], dtype=int64)

In [81]:
accuracy_score(y_pred,y_test) 

0.3355263157894737

In [82]:
print(classification_report(y_pred,y_test)) 

              precision    recall  f1-score   support

           0       0.26      0.30      0.28       107
           1       0.41      0.43      0.42       113
           2       0.38      0.31      0.34       229
           3       0.34      0.37      0.35       115
           4       0.30      0.31      0.30       196

    accuracy                           0.34       760
   macro avg       0.34      0.34      0.34       760
weighted avg       0.34      0.34      0.34       760



# Logistic Regression

In [83]:
from sklearn.linear_model import LogisticRegression 

In [84]:
lgr = LogisticRegression()

In [85]:
lgr.fit(X_train,y_train)

c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [86]:
y_pred = lgr.predict(X_test)

In [87]:
confusion_matrix(y_pred,y_test) 

array([[ 24,   3,  13,   2,   3],
       [  2,  31,   6,   2,  16],
       [ 84,  26, 118,  53,  84],
       [  2,   3,   8,  30,  10],
       [ 12,  57,  46,  38,  87]], dtype=int64)

In [88]:
accuracy_score(y_pred,y_test) 

0.3815789473684211

In [89]:
print(classification_report(y_pred,y_test)) 

              precision    recall  f1-score   support

           0       0.19      0.53      0.28        45
           1       0.26      0.54      0.35        57
           2       0.62      0.32      0.42       365
           3       0.24      0.57      0.34        53
           4       0.43      0.36      0.40       240

    accuracy                           0.38       760
   macro avg       0.35      0.47      0.36       760
weighted avg       0.48      0.38      0.40       760



# KNN

In [90]:
from sklearn.neighbors import KNeighborsClassifier

In [91]:
nc = KNeighborsClassifier(n_neighbors=3)

In [92]:
nc.fit(X_train,y_train) 

c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\neighbors\_classification.py:233: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=3)

In [93]:
y_pred = nc.predict(X_test)

In [94]:
confusion_matrix(y_pred,y_test) 

array([[52, 26, 59, 28, 49],
       [13, 41, 35, 17, 46],
       [34, 29, 59, 33, 55],
       [16, 12, 16, 27, 15],
       [ 9, 12, 22, 20, 35]], dtype=int64)

In [95]:
accuracy_score(y_pred,y_test) 

0.28157894736842104

In [96]:
print(classification_report(y_pred,y_test)) 

              precision    recall  f1-score   support

           0       0.42      0.24      0.31       214
           1       0.34      0.27      0.30       152
           2       0.31      0.28      0.29       210
           3       0.22      0.31      0.26        86
           4       0.17      0.36      0.23        98

    accuracy                           0.28       760
   macro avg       0.29      0.29      0.28       760
weighted avg       0.32      0.28      0.29       760



# SVC

In [97]:
from sklearn.svm import SVC

In [98]:
classifier_svc = SVC(kernel='linear') 

In [99]:
classifier_svc.fit(X_train,y_train) 

c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVC(kernel='linear')

In [100]:
y_pred = classifier_svc.predict(X_test)

In [101]:
confusion_matrix(y_pred,y_test) 

array([[ 29,   3,  10,   1,   3],
       [  2,  43,   6,   1,  21],
       [ 78,  23, 121,  46,  75],
       [  4,   1,  10,  37,  15],
       [ 11,  50,  44,  40,  86]], dtype=int64)

In [102]:
accuracy_score(y_pred,y_test) 

0.41578947368421054

In [103]:
print(classification_report(y_pred,y_test)) 

              precision    recall  f1-score   support

           0       0.23      0.63      0.34        46
           1       0.36      0.59      0.45        73
           2       0.63      0.35      0.45       343
           3       0.30      0.55      0.39        67
           4       0.43      0.37      0.40       231

    accuracy                           0.42       760
   macro avg       0.39      0.50      0.40       760
weighted avg       0.49      0.42      0.42       760



# Naive Bayes

In [104]:
from sklearn.naive_bayes import GaussianNB

In [105]:
nb = GaussianNB()

In [106]:
nb.fit(X_train,y_train) 

c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\utils\validation.py:1183: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GaussianNB()

In [107]:
y_pred = nb.predict(X_test)

In [108]:
confusion_matrix(y_pred,y_test) 

array([[34, 13, 39, 21, 37],
       [12, 41, 28, 16, 46],
       [46, 31, 57, 20, 46],
       [12,  9, 26, 50, 20],
       [20, 26, 41, 18, 51]], dtype=int64)

In [109]:
accuracy_score(y_pred,y_test) 

0.30657894736842106

In [110]:
print(classification_report(y_pred,y_test)) 

              precision    recall  f1-score   support

           0       0.27      0.24      0.25       144
           1       0.34      0.29      0.31       143
           2       0.30      0.28      0.29       200
           3       0.40      0.43      0.41       117
           4       0.26      0.33      0.29       156

    accuracy                           0.31       760
   macro avg       0.31      0.31      0.31       760
weighted avg       0.31      0.31      0.31       760

