In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sklearn
import pickle 

In [2]:
df = pd.read_csv('D:\My Drive\Startups.csv')
df.head()

R&D Spend  Administration  Marketing Spend       State     Profit
0  165349.20       136897.80        471784.10    New York  192261.83
1  162597.70       151377.59        443898.53  California  191792.06
2  153441.51       101145.55        407934.54     Florida  191050.39
3  144372.41       118671.85        383199.62    New York  182901.99
4  142107.34        91391.77        366168.42     Florida  166187.94

In [4]:
df.isnull().sum() 

R&D Spend          0
Administration     0
Marketing Spend    0
State              0
Profit             0
dtype: int64

In [5]:
X= df.drop(columns='Profit')
y= df['Profit']

In [6]:
X.head()

R&D Spend  Administration  Marketing Spend       State
0  165349.20       136897.80        471784.10    New York
1  162597.70       151377.59        443898.53  California
2  153441.51       101145.55        407934.54     Florida
3  144372.41       118671.85        383199.62    New York
4  142107.34        91391.77        366168.42     Florida

In [7]:
y.head()

0    192261.83
1    191792.06
2    191050.39
3    182901.99
4    166187.94
Name: Profit, dtype: float64

In [8]:
df['State'].unique()

array(['New York', 'California', 'Florida'], dtype=object)

In [9]:
X = pd.get_dummies(data=X,columns=['State'],drop_first=True)
X.head() 

R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
0  165349.20       136897.80        471784.10              0               1
1  162597.70       151377.59        443898.53              0               0
2  153441.51       101145.55        407934.54              1               0
3  144372.41       118671.85        383199.62              0               1
4  142107.34        91391.77        366168.42              1               0

In [10]:
from sklearn.preprocessing import RobustScaler
sc = RobustScaler()
X[['R&D Spend','Administration','Marketing Spend']] = sc.fit_transform(X[['R&D Spend','Administration','Marketing Spend']] )
X.head()

R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
0   1.496732        0.345355         1.522416              0               1
1   1.452113        0.697565         1.358546              0               0
2   1.303634       -0.524290         1.147203              1               0
3   1.156567       -0.097977         1.001848              0               1
4   1.119836       -0.761543         0.901764              1               0

# test train split

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=102)

In [12]:
X_train

R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
31  -0.193212        0.729778        -0.731614              0               1
33  -0.284711       -0.477784         0.011275              1               0
19   0.216789        0.749534        -1.250030              0               1
24   0.064750       -0.569635        -0.423940              0               1
10   0.468034       -0.294461         0.096638              1               0
12   0.337504        0.112392         0.218155              1               0
17   0.350370        0.544322         0.410522              0               1
30  -0.179297       -0.171693        -0.714496              1               0
42  -0.801249       -0.644839        -0.380299              0               0
5    0.953936       -0.556662         0.882330              0               1
22   0.015300        0.002018         0.532430              1               0
6    0.998345        0.595921        -0.499500              0               0
11   0.447908       -0.751841         0.217597              0               0
46  -1.163285       -0.167438         0.495967              1               0
36  -0.719797        0.105966        -0.068105              1               0
40  -0.718328       -0.101037        -0.234594              0               0
38  -0.856568       -1.380444        -0.161317              0               1
48  -1.175827       -1.725964        -1.250030              0               1
35  -0.438440       -0.915864        -0.042303              0               1
27  -0.015300        0.125629         0.825459              0               1
28  -0.113507        1.458133        -0.555730              1               0
25  -0.135996        0.409945        -0.439291              0               0
39  -0.559341       -0.966102        -0.221644              0               0
16   0.080466       -0.026811         0.303403              0               0
49  -1.184617       -0.139037        -0.984570              0               0
32  -0.156361        0.158589        -0.979209              0               0
3    1.156567       -0.097977         1.001848              0               1
18   0.303213       -0.207340         0.483069              1               0
4    1.119836       -0.761543         0.901764              1               0
7    0.928334        0.555328         0.653236              1               0
15   0.672530       -0.002018         0.288302              0               1
44  -0.824976        0.780961        -1.083520              0               0
45  -1.168397        0.035349        -1.238841              0               1
8    0.770134        0.632895         0.581170              0               1
9    0.815416       -0.341041         0.542199              0               0
43  -0.933171        0.113898        -1.041213              0               1
2    1.303634       -0.524290         1.147203              1               0
47  -1.184617        0.309577        -1.250030              0               0
14   0.760416        0.823317         0.257372              1               0
0    1.496732        0.345355         1.522416              0               1

In [13]:
y_train

31     97483.56
33     96778.92
19    122776.86
24    108552.04
10    146121.95
12    141585.52
17    125370.37
30     99937.59
42     71498.49
5     156991.12
22    110352.25
6     156122.51
11    144259.40
46     49490.75
36     90708.19
40     78239.91
38     81229.06
48     35673.41
35     96479.51
27    105008.31
28    103282.38
25    107404.34
39     81005.76
16    126992.93
49     14681.40
32     97427.84
3     182901.99
18    124266.90
4     166187.94
7     155752.60
15    129917.04
44     65200.33
45     64926.08
8     152211.77
9     149759.96
43     69758.98
2     191050.39
47     42559.73
14    132602.65
0     192261.83
Name: Profit, dtype: float64

In [14]:
X_test

R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
37  -0.469966       -1.737154        -0.092184              0               0
23  -0.089490       -0.412265         0.540948              1               0
26   0.036937        0.521418        -0.462283              1               0
20   0.051937       -0.214843         0.505076              0               0
29  -0.120740        0.737808        -0.620430              0               1
1    1.452113        0.697565         1.358546              0               0
21   0.086569        0.755842         0.511380              0               1
13   0.307158        0.311235         0.234759              0               0
34  -0.431759        0.851204        -0.011275              0               0
41  -0.732297       -0.924053        -0.283515              1               0

In [15]:
y_test

37     89949.14
23    108733.99
26    105733.54
20    118474.03
29    101004.64
1     191792.06
21    111313.02
13    134307.35
34     96712.80
41     77798.83
Name: Profit, dtype: float64

# multiple linear regression

In [16]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
model = lr.fit(X_train,y_train)
model

LinearRegression()

# prediction

In [17]:
y_pred = lr.predict(X_test)
y_pred

array([ 87945.70380182, 110085.98872324, 111615.52071114, 114130.41030041,
       102472.90309253, 186101.26707243, 116826.18732432, 125256.95283048,
        86591.67464092,  75650.68475618])

In [18]:
train_acc = lr.predict(X_train)
train_acc

array([ 98458.20825457,  98522.11944396, 117170.06832788, 114262.41990486,
       136322.46865323, 129644.75198575, 129992.14983512, 100835.66348889,
        68817.54705264, 163433.93383857, 114742.51313791, 156947.86279476,
       133715.54325794,  55738.35077629,  75620.6709182 ,  72741.84385083,
        70093.55946484,  50727.09601172,  90844.15953216, 113687.52773904,
       102455.24960438, 100525.34531715,  81949.0284317 , 114593.56868855,
        46770.65780888,  97950.06960266, 173386.7572169 , 129295.92281355,
       172485.20815396, 160198.23549838, 146469.61934938,  63195.86029978,
        48720.11881081, 151522.85436393, 152724.4710912 ,  61104.45241683,
       182240.56352741,  45220.80180389, 150016.3119981 , 191669.00493338])

# evaulton

In [19]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.9649748132881202

In [20]:
r2_score(y_train,train_acc)

0.9478393895388706

# real data prediction

In [21]:
print(sc.transform([[165349.2,136897.80,471784.10]]))

[[1.49673201 0.34535525 1.52241555]]


c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but RobustScaler was fitted with feature names
  warnings.warn(


In [22]:
lr.predict([[1.49673201,0.34535525,1.52241555,0,1]])

c:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([191669.00469578])

In [23]:
# save model
#pickle.dump(lr,open("Ml model",mode='wb'))