Numpy

In [1]:
import numpy as np

0D

In [12]:
a = np.array(5)
a

array(5)

In [13]:
print(a.shape)
print(a.size)

()
1


1D

In [17]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [18]:
print(a.shape)
print(a.size)

(4,)
4


2D

In [19]:
a = np.array([ [1,2,3], [1,2,3], [1,2,3] ])
a

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [20]:
print(a.shape)
print(a.size)

(3, 3)
9


3D

In [21]:
a = np.array([ [[1,2,3], [1,2,3], [1,2,3]], [[1,2,3], [1,2,3], [1,2,3]], [[1,2,3], [1,2,3], [1,2,3]] ]) 
a

array([[[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]],

       [[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]]])

In [22]:
print(a.shape)
print(a.size)

(3, 3, 3)
27


In [23]:
a.ndim

3

In [25]:
print(type(a))

<class 'numpy.ndarray'>


In [27]:
print(a.dtype)

int32


In [30]:
a = np.array([ [[1,2,3,4],[5,6,7,8]], [[7,5,4,3],[5,3,2,1]] ])
a

array([[[1, 2, 3, 4],
        [5, 6, 7, 8]],

       [[7, 5, 4, 3],
        [5, 3, 2, 1]]])

In [31]:
print(a.shape)
print(a.size)

(2, 2, 4)
16


Ones Matrix

1D ones

In [32]:
a = np.ones(3)
a

array([1., 1., 1.])

In [33]:
print(a.dtype)

float64


In [34]:
print(a.ndim)

1


2D ones

In [35]:
a = np.ones((2,3),dtype='int')
a

array([[1, 1, 1],
       [1, 1, 1]])

In [36]:
a = np.ones((5,3),dtype='bool')
a

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [37]:
a = np.ones((3,6),dtype='str')
a

array([['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1'],
       ['1', '1', '1', '1', '1', '1']], dtype='<U1')

Zeros Matrix

1D zeros

In [39]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [40]:
print(a.dtype)

float64


In [41]:
print(a.ndim)

1


2D zeros

In [43]:
a = np.zeros((2,5),dtype='int')
a

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [44]:
a = np.zeros((4,7),dtype='str')
a

array([['', '', '', '', '', '', ''],
       ['', '', '', '', '', '', ''],
       ['', '', '', '', '', '', ''],
       ['', '', '', '', '', '', '']], dtype='<U1')

In [45]:
a = np.zeros((2,5),dtype='bool')
a

array([[False, False, False, False, False],
       [False, False, False, False, False]])

In [48]:
a = np.zeros((4,2))
a

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [49]:
print(a.dtype)

float64


In [50]:
a = np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [53]:
a = np.arange(1,9).reshape(2,4)
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [54]:
a = np.arange(10,20).reshape(5,2)
a

array([[10, 11],
       [12, 13],
       [14, 15],
       [16, 17],
       [18, 19]])

In [55]:
a = np.arange(3,21,2).reshape(3,3)
a

array([[ 3,  5,  7],
       [ 9, 11, 13],
       [15, 17, 19]])

In [56]:
a = np.arange(1,101,10).reshape(2,5)
a

array([[ 1, 11, 21, 31, 41],
       [51, 61, 71, 81, 91]])

In [59]:
a = np.arange(100,1001,100).reshape(2,5)
print(a)

[[ 100  200  300  400  500]
 [ 600  700  800  900 1000]]


Linespace

In [61]:
linespace = np.linspace(1,11,12)
linespace

array([ 1.        ,  1.90909091,  2.81818182,  3.72727273,  4.63636364,
        5.54545455,  6.45454545,  7.36363636,  8.27272727,  9.18181818,
       10.09090909, 11.        ])

In [63]:
linespace = np.linspace(2,20,30)
linespace

array([ 2.        ,  2.62068966,  3.24137931,  3.86206897,  4.48275862,
        5.10344828,  5.72413793,  6.34482759,  6.96551724,  7.5862069 ,
        8.20689655,  8.82758621,  9.44827586, 10.06896552, 10.68965517,
       11.31034483, 11.93103448, 12.55172414, 13.17241379, 13.79310345,
       14.4137931 , 15.03448276, 15.65517241, 16.27586207, 16.89655172,
       17.51724138, 18.13793103, 18.75862069, 19.37931034, 20.        ])

In [70]:
linespace = np.linspace(2,20,30,endpoint=False,retstep=True)
linespace

(array([ 2. ,  2.6,  3.2,  3.8,  4.4,  5. ,  5.6,  6.2,  6.8,  7.4,  8. ,
         8.6,  9.2,  9.8, 10.4, 11. , 11.6, 12.2, 12.8, 13.4, 14. , 14.6,
        15.2, 15.8, 16.4, 17. , 17.6, 18.2, 18.8, 19.4]),
 0.6)

In [64]:
linespace = np.linspace(1,10,20)
linespace

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [66]:
linespace = np.linspace(1,10,20,endpoint=False)
linespace

array([1.  , 1.45, 1.9 , 2.35, 2.8 , 3.25, 3.7 , 4.15, 4.6 , 5.05, 5.5 ,
       5.95, 6.4 , 6.85, 7.3 , 7.75, 8.2 , 8.65, 9.1 , 9.55])

In [67]:
linespace = np.linspace(1,10,20,retstep=True)
linespace

(array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
         3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
         5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
         8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ]),
 0.47368421052631576)

In [71]:
linespace = np.linspace(1,10,20,endpoint=False,retstep=True)
print(linespace)

(array([1.  , 1.45, 1.9 , 2.35, 2.8 , 3.25, 3.7 , 4.15, 4.6 , 5.05, 5.5 ,
       5.95, 6.4 , 6.85, 7.3 , 7.75, 8.2 , 8.65, 9.1 , 9.55]), 0.45)


Ravel

In [75]:
#Ravel - Any matrix convert into 1D

a = np.arange(6).reshape(3,2)
print(a)
print(a.ravel())

[[0 1]
 [2 3]
 [4 5]]
[0 1 2 3 4 5]


In [76]:
a = np.arange(16).reshape(4,4)
print(a)
print(a.ravel())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


Flatten

In [86]:
#Flatten -  Any matrix convert into 1D

a = np.arange(9).reshape(3,3)
print(a)
print(a.flatten())
print(a.flatten(order='f'))

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2 3 4 5 6 7 8]
[0 3 6 1 4 7 2 5 8]


In [81]:
a = np.arange(28).reshape(2,2,7)
print(a)

[[[ 0  1  2  3  4  5  6]
  [ 7  8  9 10 11 12 13]]

 [[14 15 16 17 18 19 20]
  [21 22 23 24 25 26 27]]]


In [82]:
print(a.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27]


In [84]:
print(a.flatten(order='f'))

[ 0 14  7 21  1 15  8 22  2 16  9 23  3 17 10 24  4 18 11 25  5 19 12 26
  6 20 13 27]


In [85]:
print(a.flatten(order='k'))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27]


Array Operation & Function

In [128]:
a = np.arange(1,21).reshape(4,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [43]:
b = np.arange(21,41).reshape(4,5)
b

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [48]:
c = a+b
c

array([[22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50],
       [52, 54, 56, 58, 60]])

In [9]:
np.add(a,b)

array([[22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40],
       [42, 44, 46, 48, 50],
       [52, 54, 56, 58, 60]])

In [10]:
a-b

array([[-20, -20, -20, -20, -20],
       [-20, -20, -20, -20, -20],
       [-20, -20, -20, -20, -20],
       [-20, -20, -20, -20, -20]])

In [11]:
np.subtract(a,b)

array([[-20, -20, -20, -20, -20],
       [-20, -20, -20, -20, -20],
       [-20, -20, -20, -20, -20],
       [-20, -20, -20, -20, -20]])

In [12]:
a*b

array([[ 21,  44,  69,  96, 125],
       [156, 189, 224, 261, 300],
       [341, 384, 429, 476, 525],
       [576, 629, 684, 741, 800]])

In [13]:
np.multiply(a,b)

array([[ 21,  44,  69,  96, 125],
       [156, 189, 224, 261, 300],
       [341, 384, 429, 476, 525],
       [576, 629, 684, 741, 800]])

In [24]:
a*a*b

array([[     194481,     3748096,    22667121,    84934656,   244140625],
       [  592240896,  1275989841, -1777336320,   345503345,  -489934592],
       [  636369073,   268435456,  -488648687,  -202923776, -1340270703],
       [-1593835520,  1912978225,  -154095360,   842233841,  1578106880]])

In [25]:
b/a

array([[ 21.,  44.,  69.,  96., 125.],
       [156., 189., 224., 261., 300.],
       [341., 384., 429., 476., 525.],
       [576., 629., 684., 741., 800.]])

In [17]:
np.divide(b,a)

array([[21.        , 11.        ,  7.66666667,  6.        ,  5.        ],
       [ 4.33333333,  3.85714286,  3.5       ,  3.22222222,  3.        ],
       [ 2.81818182,  2.66666667,  2.53846154,  2.42857143,  2.33333333],
       [ 2.25      ,  2.17647059,  2.11111111,  2.05263158,  2.        ]])

In [3]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
b = np.arange(1,10).reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
a.dot(b) #1(1)+2(4)+3(7)=1+8+21=30

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [6]:
a.T #transpose of matrix

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [138]:
np.concatenate((a,b)) #join two array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [139]:
np.vstack((a,b)) #join two array vertically

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [140]:
np.hstack((a,b)) #join two array horizontally

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [141]:
x = np.arange(1,25).reshape(4,6)
x

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [142]:
np.split(x,2) #split array into two parts

[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]])]

In [145]:
np.vsplit(x,2) #split array into two parts vertically

[array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]])]

In [146]:
np.hsplit(x,2) #split array into two parts horizontally

[array([[ 1,  2,  3],
        [ 7,  8,  9],
        [13, 14, 15],
        [19, 20, 21]]),
 array([[ 4,  5,  6],
        [10, 11, 12],
        [16, 17, 18],
        [22, 23, 24]])]

In [147]:
np.hsplit(x,3)

[array([[ 1,  2],
        [ 7,  8],
        [13, 14],
        [19, 20]]),
 array([[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22]]),
 array([[ 5,  6],
        [11, 12],
        [17, 18],
        [23, 24]])]

In [154]:
np.split(x,6,axis=1)

[array([[ 1],
        [ 7],
        [13],
        [19]]),
 array([[ 2],
        [ 8],
        [14],
        [20]]),
 array([[ 3],
        [ 9],
        [15],
        [21]]),
 array([[ 4],
        [10],
        [16],
        [22]]),
 array([[ 5],
        [11],
        [17],
        [23]]),
 array([[ 6],
        [12],
        [18],
        [24]])]

In [155]:
np.split(x,4,axis=0)

[array([[1, 2, 3, 4, 5, 6]]),
 array([[ 7,  8,  9, 10, 11, 12]]),
 array([[13, 14, 15, 16, 17, 18]]),
 array([[19, 20, 21, 22, 23, 24]])]

In [156]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [157]:
a.max()

9

In [158]:
a.min()

1

In [159]:
a.argmax()

8

In [160]:
a.argmin()

0

In [51]:
k = np.arange(21,36).reshape(3,5)
k

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [53]:
print(k.max()) #max element
print(k.min()) #min element
print(k.argmax()) #(3*5)-1
print(k.argmin()) #always 0

35
21
14
0


In [62]:
print(k.max(axis=0)) #last row of array
print(k.max(axis=1)) #last column of array
print(k.min(axis=0)) #first row of array
print(k.min(axis=1)) #first column of array
print(k.min(axis=-1)) #same as axis 1

[31 32 33 34 35]
[25 30 35]
[21 22 23 24 25]
[21 26 31]
[21 26 31]


In [76]:
print(k.sum()) #sum of all array element
print(np.sum(k))

print(k.sum(axis=1)) #sum of all row (21+22+23+24+25 26+27+28+29+30 31+32+33+34+35)
print(k.sum(axis=0)) #sum of all column(21+26+31 22+27+32 23+28+33 24+29+34 25+30+35)
print(np.sum(k,axis=0))

print(k.mean()) #mean of all array element(420/15)
print(np.mean(k))

print(k.mean(axis=1)) #mean of all row (115/5 140/5 165/5)
print(k.mean(axis=0)) #mean of all column (78/3 81/3 84/3 87/3 90/3)
print(np.mean(k,axis=0))

420
420
[115 140 165]
[78 81 84 87 90]
[78 81 84 87 90]
28.0
28.0
[23. 28. 33.]
[26. 27. 28. 29. 30.]
[26. 27. 28. 29. 30.]


In [87]:
k

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [88]:
np.square(k) #square of every element

array([[ 441,  484,  529,  576,  625],
       [ 676,  729,  784,  841,  900],
       [ 961, 1024, 1089, 1156, 1225]])

In [80]:
np.sqrt(k) #square root of every elment

array([[4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ],
       [5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558],
       [5.56776436, 5.65685425, 5.74456265, 5.83095189, 5.91607978]])

In [93]:
np.var(k) #variance (mean( abs(x-x.mean())**2 ))

18.666666666666668

In [83]:
np.std(k) #standard deviation (sqrt(variance))

4.320493798938574

In [102]:
np.exp(k) #exponential

array([[1.31881573e+09, 3.58491285e+09, 9.74480345e+09, 2.64891221e+10,
        7.20048993e+10],
       [1.95729609e+11, 5.32048241e+11, 1.44625706e+12, 3.93133430e+12,
        1.06864746e+13],
       [2.90488497e+13, 7.89629602e+13, 2.14643580e+14, 5.83461743e+14,
        1.58601345e+15]])

In [103]:
np.log(k) #log value

array([[3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582],
       [3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738],
       [3.4339872 , 3.4657359 , 3.49650756, 3.52636052, 3.55534806]])

In [104]:
np.log10(k) #log10 value

array([[1.32221929, 1.34242268, 1.36172784, 1.38021124, 1.39794001],
       [1.41497335, 1.43136376, 1.44715803, 1.462398  , 1.47712125],
       [1.49136169, 1.50514998, 1.51851394, 1.53147892, 1.54406804]])

In [99]:
a = np.array([[2,3],[4,5]])
a

array([[2, 3],
       [4, 5]])

In [100]:
# calculating variance
# mean = (2+3+4+5)/4 = 3.5 --> 4 is total no. of element in array
# x = (2-3.5)**2 + (3-3.5)**2 + (4-3.5)**2 + (5-3.5)**2 = (-1.5)**2 + (-0.5)**2 + (0.5)**2 + (1.5)**2 = 2.25 + 0.25 + 0.25 + 2.25 = 5
# var = x/4 = 5/4 = 1.25

np.var(a)

1.25

In [101]:
# calculating standard deviation
# std = sqrt(var) = sqrt(1.25) = 1.1180339887

np.std(a)

1.118033988749895

In [105]:
k

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [113]:
print(k[0,0]) #[row,column]
print(k[0,3])
print(k[1,3])
print(k[1,4])
print(k[2,2])
print(k[2,1])

21
24
29
30
33
32


In [114]:
k

array([[21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [125]:
print(k[0:2,0:2],"\n") #[row:column]
print(k[0:1,0:2],"\n")
print(k[1:3,1:4],"\n")
print(k[0:,3:])

[[21 22]
 [26 27]] 

[[21 22]] 

[[27 28 29]
 [32 33 34]] 

[[24 25]
 [29 30]
 [34 35]]


Value of Trigonometric Function

In [161]:
np.sin(90)

0.8939966636005579

In [162]:
np.tan(45)

1.6197751905438615

In [164]:
np.sin(np.pi)

1.2246467991473532e-16

In [165]:
np.sin(np.pi/3)

0.8660254037844386

In [169]:
np.cos(90)

-0.4480736161291701

In [170]:
np.tan(np.pi/4)

0.9999999999999999

Random Function

In [191]:
a = np.random.random(10) #default 1D array 
print(a)
print(a.shape)

[0.3659007  0.18214692 0.81472948 0.76506534 0.36249238 0.8051466
 0.70331761 0.2968913  0.04162614 0.90055502]
(10,)


In [192]:
a = np.random.random(24)
print(a)
print(a.shape)

[0.03441627 0.92167268 0.02069415 0.80340328 0.06853555 0.65891444
 0.06148941 0.08476092 0.22929464 0.48852035 0.05238294 0.15288633
 0.15700971 0.82932723 0.89476544 0.25037204 0.75956038 0.90599966
 0.06771504 0.6817611  0.90022843 0.68509641 0.42859357 0.40912378]
(24,)


In [193]:
a = np.random.random(24).reshape(4,6)
print(a)
print(a.shape)

[[0.27347829 0.89478938 0.86375548 0.09713638 0.91309997 0.28288906]
 [0.88582157 0.67951439 0.52207439 0.31881926 0.76183738 0.01253323]
 [0.8555484  0.23650145 0.44817792 0.03223781 0.78643706 0.83571036]
 [0.38030237 0.09093136 0.910669   0.00298225 0.35288471 0.27889418]]
(4, 6)


In [241]:
np.random.rand(5) #1D array

array([0.32551164, 0.1650159 , 0.39252924, 0.09346037, 0.82110566])

In [242]:
np.random.rand(3,2) #2D array

array([[0.15115202, 0.38411445],
       [0.94426071, 0.98762547],
       [0.45630455, 0.82612284]])

In [243]:
np.random.rand(3,4,2) #3D array

array([[[0.25137413, 0.59737165],
        [0.90283176, 0.53455795],
        [0.59020136, 0.03928177],
        [0.35718176, 0.07961309]],

       [[0.30545992, 0.33071931],
        [0.7738303 , 0.03995921],
        [0.42949218, 0.31492687],
        [0.63649114, 0.34634715]],

       [[0.04309736, 0.87991517],
        [0.76324059, 0.87809664],
        [0.41750914, 0.60557756],
        [0.51346663, 0.59783665]]])

In [236]:
np.random.rand(4,2,3) #3D array

array([[[0.91777412, 0.71457578, 0.54254437],
        [0.14217005, 0.37334076, 0.67413362]],

       [[0.44183317, 0.43401399, 0.61776698],
        [0.51313824, 0.65039718, 0.60103895]],

       [[0.8052232 , 0.52164715, 0.90864888],
        [0.31923609, 0.09045935, 0.30070006]],

       [[0.11398436, 0.82868133, 0.04689632],
        [0.62628715, 0.54758616, 0.819287  ]]])

In [183]:
np.random.random((4,6)) #2D array

array([[0.13230266, 0.65788717, 0.38686761, 0.12493175, 0.42067768,
        0.53014507],
       [0.80431667, 0.36596982, 0.61799179, 0.65356458, 0.96461101,
        0.81118096],
       [0.53106495, 0.134458  , 0.64551424, 0.97868357, 0.44650682,
        0.52761893],
       [0.57309071, 0.37337849, 0.08728367, 0.87407032, 0.84167357,
        0.64053587]])

In [188]:
np.random.random((3,3,3)) #3D array

array([[[0.44763475, 0.38562623, 0.72832898],
        [0.04684514, 0.00896973, 0.21689803],
        [0.50143481, 0.02030715, 0.1361316 ]],

       [[0.3017568 , 0.07168766, 0.41980414],
        [0.84216933, 0.31456296, 0.46068781],
        [0.76130083, 0.11949595, 0.90870404]],

       [[0.20590759, 0.07064935, 0.80053136],
        [0.87671455, 0.38785931, 0.77506487],
        [0.61312822, 0.44945583, 0.12518466]]])

In [189]:
np.random.random((3,2,4)) #3D array

array([[[0.15545144, 0.0345702 , 0.73309202, 0.06436501],
        [0.98120705, 0.71784775, 0.05644993, 0.45117179]],

       [[0.74031711, 0.03938687, 0.47860875, 0.55973998],
        [0.40069822, 0.84140011, 0.36979573, 0.07342866]],

       [[0.51477058, 0.82055242, 0.88712922, 0.0280461 ],
        [0.58801838, 0.32043039, 0.12066194, 0.90743112]]])

In [207]:
np.random.randint(4) #any random int within 4

2

In [210]:
np.random.randint(5,10) #any random int btw 5 to 10 (10 excluding)

7

In [220]:
np.random.randint(2,9,10) #any random int btw 2 to 9 (9 excluding) and no. of array element is 10 and it is 1D array

array([7, 2, 7, 3, 7, 8, 3, 8, 3, 5])

In [222]:
np.random.randint(1,10,(5,4)) #no.of array element is 5*4=20 and it is 2D array(5*4)

array([[1, 3, 5, 4],
       [8, 4, 7, 6],
       [9, 9, 8, 8],
       [3, 5, 3, 4],
       [5, 3, 5, 5]])

In [223]:
np.random.randint(5,20,(4,2,5)) #no. of array element is 4*2*5=40 and it is 3D array(4*2*5)

array([[[11, 13,  5,  9, 10],
        [15, 19, 12, 17,  6]],

       [[15, 13, 14, 16,  8],
        [19, 18, 13, 13,  5]],

       [[ 7,  9, 11,  9, 15],
        [19, 13, 18, 10,  5]],

       [[16, 14,  8,  6, 18],
        [ 8, 15, 17,  9, 11]]])

In [232]:
a = np.random.seed(10) #value does not change
print(a)

None


String Opn

In [8]:
s1 = 'My Name is Krupa Bhalani'
s2 = 'I Know Python Language'
print(s1,'\n',s2)

My Name is Krupa Bhalani 
 I Know Python Language


In [15]:
print(np.char.add(s1+" ",s2)) #concatenate two string

My Name is Krupa Bhalani I Know Python Language


In [16]:
print(np.char.multiply(s1+" ",4)) #s1 printing 4 times

My Name is Krupa Bhalani My Name is Krupa Bhalani My Name is Krupa Bhalani My Name is Krupa Bhalani 


In [20]:
print(np.char.lower(s1)) #every char of string in lower case
print(np.char.upper(s1)) #every char of string in upper case
print(np.char.lower(s2))
print(np.char.upper(s2))

my name is krupa bhalani
MY NAME IS KRUPA BHALANI
i know python language
I KNOW PYTHON LANGUAGE


In [24]:
print(np.char.center(s1,100)) #create space
print(np.char.center(s2,100))
print(np.char.center(s1,100,fillchar='_')) #space fill by givien char
print(np.char.center(s2,100,fillchar='.'))

                                      My Name is Krupa Bhalani                                      
                                       I Know Python Language                                       
______________________________________My Name is Krupa Bhalani______________________________________
.......................................I Know Python Language.......................................


In [26]:
print(np.char.split(s1,'is')) #spliting string by givien char
print(np.char.split(s2,' '))

['My Name ', ' Krupa Bhalani']
['I', 'Know', 'Python', 'Language']


In [38]:
print(np.char.splitlines('Hello\nWorld')) #split where \n
print(np.char.splitlines('Krupa\nBhalani'))

['Hello', 'World']
['Krupa', 'Bhalani']


In [40]:
st1 = 'DMY'
st2 = 'dmy'
st3 = 'DmY'
print(np.char.join([':','/','-'],[st1,st2,st3])) #join str using givien char
print(np.char.join(['*','^'],[st3,st1]))

['D:M:Y' 'd/m/y' 'D-m-Y']
['D*m*Y' 'D^M^Y']


In [42]:
print(np.char.replace(s1,'a','A')) #replae string char
print(np.char.replace(s2,' ','-'))

My NAme is KrupA BhAlAni
I-Know-Python-Language


In [46]:
print(np.char.equal(s1,s2)) #to check str is eual or not
print(np.char.equal(st1,st3))
st4 = 'DmY'
print(np.char.equal(st3,st4))

False
False
True


In [47]:
print(s1)
print(s2)

My Name is Krupa Bhalani
I Know Python Language


In [52]:
print(np.char.find(s1,'a')) #give first index of given char and space also count
print(np.char.find(s2,'p')) #whenever given char is not there that time it return -1
print(np.char.find(s2,'P'))
print(np.char.find(s1,'k'))
print(np.char.find(s1,'K'))

4
-1
7
-1
11


In [55]:
print(np.char.index(s1,'a')) #give first index of given char and space also count
print(np.char.index(s2,'P'))
print(np.char.index(s1,'K'))
# print(np.char.find(s2,'p')) --> whenever given char is not there that time it return value error "substring not found"

4
7
11


In [60]:
print(np.char.count(s1,'a')) #count given char in str
print(np.char.count(s1,'a',start=0,end=15)) #15 exclud
print(np.char.count(s1,'q'))
print(np.char.count(s1,'A'))

4
1
0
0
