In [2]:
import pandas as pd 
import matplotlib.pyplot as plt 

In [16]:
df = pd.read_csv(r"D:\My Drive\creditcard.csv")
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28  Amount  Class  
0 -0.189115  0.133558 -0.021053  149.62      0  
1  0.125895 -0.008983  0.014724    2.69      0  
2 -0.139097 -0.055353 -0.059752  378.66      0  
3 -0.221929  0.062723  0.061458  123.50      0  
4  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [17]:
df.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [19]:
x = df[['Amount']]
x.head()

Amount
0  149.62
1    2.69
2  378.66
3  123.50
4   69.99

In [20]:
y = df[['Class']]
y.head()

Class
0      0
1      0
2      0
3      0
4      0

In [21]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=2) 

In [22]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression() 

In [23]:
lr.fit(x_train,y_train) 

LinearRegression()

In [24]:
y_pred = lr.predict(x_test) 

In [25]:
from sklearn.metrics import r2_score 

In [26]:
r2_score(y_pred,y_test) 

-16219.493872025469

In [27]:
X = df.drop(columns='Class')
X 

Time         V1         V2        V3        V4        V5  \
0            0.0  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
1            0.0   1.191857   0.266151  0.166480  0.448154  0.060018   
2            1.0  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
3            1.0  -0.966272  -0.185226  1.792993 -0.863291 -0.010309   
4            2.0  -1.158233   0.877737  1.548718  0.403034 -0.407193   
...          ...        ...        ...       ...       ...       ...   
284802  172786.0 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  172787.0  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  172788.0   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  172788.0  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  172792.0  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V20       V21  \
0       0.462388  0.239599  0.098698  0.363787  ...  0.251412 -0.018307   
1      -0.082361 -0.078803  0.085102 -0.255425  ... -0.069083 -0.225775   
2       1.800499  0.791461  0.247676 -1.514654  ...  0.524980  0.247998   
3       1.247203  0.237609  0.377436 -1.387024  ... -0.208038 -0.108300   
4       0.095921  0.592941 -0.270533  0.817739  ...  0.408542 -0.009431   
...          ...       ...       ...       ...  ...       ...       ...   
284802 -2.606837 -4.918215  7.305334  1.914428  ...  1.475829  0.213454   
284803  1.058415  0.024330  0.294869  0.584800  ...  0.059616  0.214205   
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.001396  0.232045   
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.127434  0.265245   
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.382948  0.261057   

             V22       V23       V24       V25       V26       V27       V28  \
0       0.277838 -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053   
1      -0.638672  0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724   
2       0.771679  0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752   
3       0.005274 -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458   
4       0.798278 -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   
...          ...       ...       ...       ...       ...       ...       ...   
284802  0.111864  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731   
284803  0.924384  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   
284804  0.578229 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   
284805  0.800049 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   
284806  0.643078  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649   

        Amount  
0       149.62  
1         2.69  
2       378.66  
3       123.50  
4        69.99  
...        ...  
284802    0.77  
284803   24.79  
284804   67.88  
284805   10.00  
284806  217.00  

[284807 rows x 30 columns]

In [28]:
y = df['Class'] 
y 

0         0
1         0
2         0
3         0
4         0
         ..
284802    0
284803    0
284804    0
284805    0
284806    0
Name: Class, Length: 284807, dtype: int64

In [29]:
from sklearn.preprocessing import RobustScaler
sc = RobustScaler()
X[['Time','Amount']] = sc.fit_transform(X[['Time','Amount']] )
X 

Time         V1         V2        V3        V4        V5  \
0      -0.994983  -1.359807  -0.072781  2.536347  1.378155 -0.338321   
1      -0.994983   1.191857   0.266151  0.166480  0.448154  0.060018   
2      -0.994972  -1.358354  -1.340163  1.773209  0.379780 -0.503198   
3      -0.994972  -0.966272  -0.185226  1.792993 -0.863291 -0.010309   
4      -0.994960  -1.158233   0.877737  1.548718  0.403034 -0.407193   
...          ...        ...        ...       ...       ...       ...   
284802  1.034951 -11.881118  10.071785 -9.834783 -2.066656 -5.364473   
284803  1.034963  -0.732789  -0.055080  2.035030 -0.738589  0.868229   
284804  1.034975   1.919565  -0.301254 -3.249640 -0.557828  2.630515   
284805  1.034975  -0.240440   0.530483  0.702510  0.689799 -0.377961   
284806  1.035022  -0.533413  -0.189733  0.703337 -0.506271 -0.012546   

              V6        V7        V8        V9  ...       V20       V21  \
0       0.462388  0.239599  0.098698  0.363787  ...  0.251412 -0.018307   
1      -0.082361 -0.078803  0.085102 -0.255425  ... -0.069083 -0.225775   
2       1.800499  0.791461  0.247676 -1.514654  ...  0.524980  0.247998   
3       1.247203  0.237609  0.377436 -1.387024  ... -0.208038 -0.108300   
4       0.095921  0.592941 -0.270533  0.817739  ...  0.408542 -0.009431   
...          ...       ...       ...       ...  ...       ...       ...   
284802 -2.606837 -4.918215  7.305334  1.914428  ...  1.475829  0.213454   
284803  1.058415  0.024330  0.294869  0.584800  ...  0.059616  0.214205   
284804  3.031260 -0.296827  0.708417  0.432454  ...  0.001396  0.232045   
284805  0.623708 -0.686180  0.679145  0.392087  ...  0.127434  0.265245   
284806 -0.649617  1.577006 -0.414650  0.486180  ...  0.382948  0.261057   

             V22       V23       V24       V25       V26       V27       V28  \
0       0.277838 -0.110474  0.066928  0.128539 -0.189115  0.133558 -0.021053   
1      -0.638672  0.101288 -0.339846  0.167170  0.125895 -0.008983  0.014724   
2       0.771679  0.909412 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752   
3       0.005274 -0.190321 -1.175575  0.647376 -0.221929  0.062723  0.061458   
4       0.798278 -0.137458  0.141267 -0.206010  0.502292  0.219422  0.215153   
...          ...       ...       ...       ...       ...       ...       ...   
284802  0.111864  1.014480 -0.509348  1.436807  0.250034  0.943651  0.823731   
284803  0.924384  0.012463 -1.016226 -0.606624 -0.395255  0.068472 -0.053527   
284804  0.578229 -0.037501  0.640134  0.265745 -0.087371  0.004455 -0.026561   
284805  0.800049 -0.163298  0.123205 -0.569159  0.546668  0.108821  0.104533   
284806  0.643078  0.376777  0.008797 -0.473649 -0.818267 -0.002415  0.013649   

          Amount  
0       1.783274  
1      -0.269825  
2       4.983721  
3       1.418291  
4       0.670579  
...          ...  
284802 -0.296653  
284803  0.038986  
284804  0.641096  
284805 -0.167680  
284806  2.724796  

[284807 rows x 30 columns]

In [30]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=102) 

In [31]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
model = lr.fit(X_train,y_train)
model 

LinearRegression()

In [32]:
y_pred = lr.predict(X_test)
y_pred 

array([-0.00013177, -0.00037183, -0.00226212, ...,  0.00060668,
       -0.00064795,  0.00270641])

In [33]:
train_acc = lr.predict(X_train)
train_acc 

array([-7.47212632e-04,  8.62182723e-03, -9.94805644e-05, ...,
       -3.80585816e-03,  2.85046283e-03, -8.44502767e-04])

In [34]:
r2_score(y_test,y_pred) 

0.5351592247195285

In [35]:
r2_score(y_train,train_acc) 

0.5151398965312519

In [36]:
from sklearn.preprocessing import PolynomialFeatures 

In [37]:
poly = PolynomialFeatures(degree=2)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test) 

In [38]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
model = lr.fit(X_train_poly,y_train) 

In [39]:
y_pred =lr.predict(X_test_poly)
y_pred 

array([-1.10917734e-03, -9.25793788e-04,  3.04794632e-03, ...,
       -8.60475064e-04,  3.10091015e-04, -5.35885252e-05])

In [40]:
train_acc = lr.predict(X_train_poly)
train_acc 

array([ 0.00034308,  0.00832829,  0.0007156 , ..., -0.00079392,
       -0.00257522,  0.00025892])

In [41]:
r2_score(y_test,y_pred) 

0.720900639243963

In [42]:
r2_score(y_train,train_acc) 

0.6951433928539523

In [43]:
from sklearn.tree import DecisionTreeClassifier 

In [44]:
classifier = DecisionTreeClassifier(criterion='entropy',random_state=0) #gini or entropy
classifier.fit(X_train,y_train) 

DecisionTreeClassifier(criterion='entropy', random_state=0)

In [45]:
y_pred = classifier.predict(X_test)
y_pred 

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [46]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
confusion_matrix(y_pred,y_test) 

array([[85252,    33],
       [   34,   124]], dtype=int64)

In [47]:
accuracy_score(y_pred,y_test) 

0.9992158515033414

In [48]:
print(classification_report(y_pred,y_test)) 

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     85285
           1       0.79      0.78      0.79       158

    accuracy                           1.00     85443
   macro avg       0.89      0.89      0.89     85443
weighted avg       1.00      1.00      1.00     85443



In [54]:
from sklearn.linear_model import LinearRegression
lr=LinearRegression()
lr.fit(X_train,y_train)

LinearRegression()

In [55]:
y_pred=lr.predict(X_test) 

In [56]:
from sklearn.metrics import r2_score
from sklearn.metrics import mean_squared_error
import numpy as np 

In [57]:
print("R2_score: ",r2_score(y_test,y_pred))
print("MSE: ",np.sqrt(mean_squared_error(y_test,y_pred))) 

R2_score:  0.5351592247195285
MSE:  0.029198753996917747


In [60]:
#Ridge
from sklearn.linear_model import Ridge
r=Ridge(alpha=0.0001) 
r.fit(x_train,y_train) 
y_pred1=lr.predict(X_test) 
print("R2_score: ",r2_score(y_test,y_pred1))
print("MSE: ",np.sqrt(mean_squared_error(y_test,y_pred1))) 

R2_score:  0.5351592247195285
MSE:  0.029198753996917747


In [61]:
#Lasso
from sklearn.linear_model import Lasso 
reg=Lasso(alpha=0.01)
reg.fit(X_train,y_train)
y_pred=reg.predict(X_test)
r2_score(y_test,y_pred)  

0.059785809827269665

In [62]:
#ElasticNet
from sklearn.linear_model import ElasticNet 
reg=ElasticNet(alpha=0.05,l1_ratio=0.05)
reg.fit(X_train,y_train)
y_pred=reg.predict(X_test)
r2_score(y_test,y_pred) 

0.4663774212137497